var zh = {
  ScanDirection: "扫描方向",
  ParkingOutDirection: "泊出方向",
  MarkingExist: "有无标线",
  BorderVehicleExist: "有无边界车辆",
  EdgeZeroState: "Edge0状态",
  EdgeOneState: "Edge1状态",
  ParkingSpaceSize: "车位大小",
  EdgeParkingSpaceExist: "边界车另一侧是否有车位",
  CurbStoneExist: "有无路沿石",
  ParkingSpaceType: "车位类型",
  left: "左侧",
  right: "右侧",
  you: "有",
  wu: "无",
  empty: "无",
  biaozhun: "标准",
  yaxian: "车轮压线",
  pingpian30: "平偏30cm",
  qiang: "墙",
  zhu: "柱",
  qingxie5: "倾斜5度",
  da: "大车位",
  zhong: "中车位",
  xiao: "小车位",
  er: "两个车位",
  pingxing: "平行",
  shuzhi: "竖直",
  xiexiang: "斜向",
  load: "载入",
  save: "保存"
},
  en = {
    ScanDirection: "Scan direction",
    ParkingOutDirection: "Parking out direction",
    MarkingExist: "Exist marking",
    BorderVehicleExist: "Exist boundary vehicles",
    EdgeZeroState: "Edge0 state",
    EdgeOneState: "Edge1 state",
    ParkingSpaceSize: "parking space size",
    EdgeParkingSpaceExist: "Exist parking space on the other side of the boundary vehicle",
    CurbStoneExist: "Exist curb stone",
    ParkingSpaceType: "Parking space type",
    left: "Left",
    right: "Right",
    you: "Yes",
    wu: "No",
    empty: "Empty",
    biaozhun: "Standard",
    yaxian: "Wheel on line",
    pingpian30: "Parallel 30cm",
    qiang: "Wall",
    zhu: "Pillar",
    qingxie5: "Tilt 5 degree",
    da: "Large parking space",
    zhong: "Middle parking space",
    xiao: "Small parking space",
    er: "Two parking spaces",
    pingxing: "Parallel",
    shuzhi: "Verticle",
    xiexiang: "Oblique",
    load: "Load",
    save: "Save"
  };