var en = {
  enabled: "Enabled",
  vehicle_start_stop: "Vehicle start/stop",
  vehicle_start: "Vehicle start",
  vehicle_stop: "Vehicle stop",
  reversing: "Reversing",
  emergency_break: "Emergency brake",
  decel: "Decel[m/s²]:",
  curvature: "Curvature [1/m]:",
  time: "Time [s]:",
  curve: "Curve",
  min_cure: "Min curvature :",
  max_cure: "Max curvature :",
  up_down_slope: "Up/Down slope",
  up_slope: "Up slope",
  down_slope: "Down slope",
  pitch: "Pitch [°]:",
  sport: "Spot",
  tollgate: "Tollgate",
  distance: "Distance [m] : ",
  service_area: "Service area",
  crossing: "Crossing",
  roundabout: "Roundabout",
  bridge: "Bridge",
  gnss_imu: "GNSS-IMU Channel : ",
  gnss_imu_sen_a: "GNSS-IMU Sensor A",
  gnss_imu_sen_b: "GNSS-IMU Sensor B",
  gnss_imu_sen_c: "GNSS-IMU Sensor C",
  gnss_imu_sen_d: "GNSS-IMU Sensor D",
  gnss_imu_sen_e: "GNSS-IMU Sensor E",
  gnss_imu_sen_f: "GNSS-IMU Sensor F",
  tunnel:"Tunnel",
  curv_time:"Time[s]:"
},
cn = {
  gnss_imu_sen_a: "组合惯导传感器 A",
  gnss_imu_sen_b: "组合惯导传感器 B",
  gnss_imu_sen_c: "组合惯导传感器 C",
  gnss_imu_sen_d: "组合惯导传感器 D",
  gnss_imu_sen_e: "组合惯导传感器 E",
  gnss_imu_sen_f: "组合惯导传感器 F",
  gnss_imu: "组合惯导通道 : ",
  enabled: "启用",
  vehicle_start_stop: "车辆启动/停止",
  vehicle_start: "车辆启动",
  vehicle_stop: "车辆停止",
  reversing: "倒车",
  emergency_break: "紧急制动",
  decel: "减速度[米/二次方秒]:",
  curvature: "曲率 [1/米]",
  time: "时长 [秒]:",
  curve: "曲率 ",
  min_cure: "最小曲率 [1/m] :",
  max_cure: "最大曲率 [1/m] :",
  up_down_slope: "向上/向下的斜坡",
  up_slope: "上坡",
  down_slope: "下坡",
  pitch: "坡度 [度]:",
  sport: "地标",
  tollgate: "收费站",
  distance: "距离 [米] : ",
  service_area: "服务区",
  crossing: "路口",
  roundabout: "环岛",
  bridge: "桥",
  tunnel:"隧道",
  curv_time:"保持时长[秒]:"
};