var cn = {
  lfEnable: "启动",
  datumLanesChannel:"基准车道线通道:",
  fusionLanesChannel:"融合车道线通道:",
  matchMode:"匹配模式:",
  matchThresh:"匹配阈值:",
  absZeroPowerLimit: "零次项系数绝对值阈值:",
  absFirstPowerLimit: "一次项系数绝对值阈值:",
  absSecondPowerLimit: "二次项系数绝对值阈值:",
  absThirdPowerLimit: "三次项系数绝对值阈值:",
  fusedLanesChannel:"融合后车道线通道:",
},
  en = {
    lfEnable: "Enable",
    datumLanesChannel:"Datum lanes channel:",
    fusionLanesChannel:"Fusion lanes channel:",
    matchMode:"Match mode:",
    matchThresh:"Match threshold:",
    absZeroPowerLimit: "Zero power absolute max:",
    absFirstPowerLimit: "First power absolute max:",
    absSecondPowerLimit: "Second power absolute max:",
    absThirdPowerLimit: "Third power absolute max:",
    fusedLanesChannel:"Fused lanes channel:",
  }