var cn = {
    not_config: "<未配置>",
    source: "来源",
    park_slot_file_path: "停车槽文件路径(json):",
    processing: "处理",
    gnss_imu_input_channel: "GNSS-IMU输入通道:",
    traffic_output_channel: "交通信息输出通道:",
    empty: "<空>",
    convert: "转换",
    slot_id: "位置id:",
    signals: "信号",
    target_points: "目标点:",
    disabled: "(禁用)",
    traffic_sample_a: "交通样本 A",
    traffic_sample_b: "交通样本 B",
    traffic_sample_c: "交通样本 C",
    traffic_sample_d: "交通样本 D",
  },
  en = {
    disabled: "(Disabled)",
    traffic_sample_a: "Traffic Sample A",
    traffic_sample_b: "Traffic Sample B",
    traffic_sample_c: "Traffic Sample C",
    traffic_sample_d: "Traffic Sample D",
    target_points: "Target points:",
    slot_id: "Slot id:",
    signals: "Signals",
    convert: "Convert",
    not_config: "<Not Configured>",
    source: "Source",
    park_slot_file_path: "Parking slot file path(json):",
    processing: "Processing",
    gnss_imu_input_channel: "GNSS-IMU input channel:",
    traffic_output_channel: "Traffic output channel:",
    empty: "(Empty)"
  };