var cn = {
    enabled: "启用",
    not_config: "<未配置>",
    data_path:"数据路径:",
    not_available:": (不可用)",
    processing:"进程",
    subject_gnss:"主车惯导样本通道:",
    output_channel:"输出惯导样本通道:",
    sync_object:"同步目标",
    import_tool:"目标物数据导入工具",
    import:"导入",
    object:"目标物",
    data_path:"数据路径:",
    import_gnss:"导入惯导样本通道:",
    length:"本车长度[米]:",
    width:"本车宽度[米]:",
  },
  en = {
    enabled: "Enabled",
    not_config: "<Not Configured>",
    data_path:"Data Path:",
    not_available:": (Not available)",
    processing:"Processing",
    subject_gnss:"Subject GNSS-IMU Channel:",
    output_channel:"Output GNSS-IMU Channel:",
    sync_object:"Sync Object",
    import_tool:"Object Data Import Tool",
    import:"Import",
    object:"Object",
    data_path:"Data Path:",
    import_gnss:"Import GNSS-IMU Channel:",
    length:"Vehicle Length[m]:",
    width:"Vehicle Width[m]:",
  };