var cn = {
  device: "设备",
  connect: " 连接",
  ip: "IP地址:",
  port: "端口号:",
  processing: "处理",
  out_channel: "目标物输出通道:",
  freespace_channel: "可行驶区域输出通道:",
  disabled: "(Disabled)",
  attention_object_channel: "一度目标物输出通道:",
  lane_channel: "车道线输出通道:",
  point_cloud_channel: "点云输出通道:",
  origin: "原始点 [m]:",
  pos_offset: "偏移位置[°]:",
  pitch: "俯仰角",
  roll: "翻滚角",
  yaw: "偏航角"
},
en = {
  device: "Device",
  connect: " Connect",
  ip: "IP:",
  port: "Port:",
  processing: "Processing",
  out_channel: "Output Objects:",
  freespace_channel: "Output Freespace:",
  disabled: "(Disabled)",
  attention_object_channel: "Output Attention Object:",
  lane_channel: "Output Lanes:",
  point_cloud_channel: "Output Point Cloud:",
  origin: "Origin [m]:",
  pos_offset: "Pos Offset[°]:",
  pitch: "Pitch",
  roll: "Roll",
  yaw: "Yaw"
}