var cn = {
    enabled: "启用",
    final_msg: "帧尾报文: ",
    not_config: "<未配置>",
    sensors: "传感器:",
    add: "添加",
    remove_all: "移除所有",
    move_up: "上移",
    move_down: "下移",
    remove: "移除",
    dis_signal: "距离信号:",
    origin_x: "原点X[m]: ",
    origin_y: "原点Y[m]: ",
    orient: "朝向[°]: ",
    angle_alpha: "α角度值[°]: ",
    angle_beta: "β角度值[°]: ",
    range_alpha: "α探测范围[m]: ",
    range_beta: "β探测范围[m]: "
  },
  en = {
    enabled: "Enabled",
    final_msg: "Final msg: ",
    not_config: "<Not Configured>",
    sensors: "Sensors:",
    add: "Add",
    remove_all: "Remove all",
    move_up: "Move up",
    move_down: "Move down",
    remove: "Remove",
    dis_signal: "Distance signal:",
    origin_x: "Origin X [m]: ",
    origin_y: "Origin Y [m]: ",
    orient: "Orientation [°]: ",
    angle_alpha: "Angle α [°]: ",
    angle_beta: "Angle β [°]: ",
    range_alpha: "Range α [m]: ",
    range_beta: "Range β [m]: "
  };