let cn = {
  rear_left: "左后",
  rear_right: "右后",
  front_left: "左前",
  front_right: "右前",
  output_channel: "输出通道:",
  origin: "原点 [m]:",
  can_channel: "CAN 通道: ",
  position: "位置 [m]:",
  orie: "朝向 [deg]:",
  output_raw_vel: "输出原始速度和加速度",
  disabled: "(禁用)",
  obj_sen_a: "目标物传感器 A",
  obj_sen_b: "目标物传感器 B",
  obj_sen_c: "目标物传感器 C",
  obj_sen_d: "目标物传感器 D",
  obj_sen_e: "目标物传感器 E",
  obj_sen_f: "目标物传感器 F",
  obj_sen_g: "目标物传感器 G",
  obj_sen_h: "目标物传感器 H",
  obj_sen_i: "目标物传感器 I",
  obj_sen_j: "目标物传感器 J",
  obj_sen_k: "目标物传感器 K",
  obj_sen_l: "目标物传感器 L",
},
  en = {
      disabled: "(Disabled)",
      obj_sen_a: "Object sensor A",
      obj_sen_b: "Object sensor B",
      obj_sen_c: "Object sensor C",
      obj_sen_d: "Object sensor D",
      obj_sen_e: "Object sensor E",
      obj_sen_f: "Object sensor F",
      obj_sen_g: "Object sensor G",
      obj_sen_h: "Object sensor H",
      obj_sen_i: "Object sensor I",
      obj_sen_j: "Object sensor J",
      obj_sen_k: "Object sensor K",
      obj_sen_l: "Object sensor L",
      rear_left: "Rear Left",
      rear_right: "Rear Right",
      front_left: "Front Left",
      front_right: "Front Right",
      output_channel: "Output channel:",
      origin: "Origin [m]:",
      can_channel: "CAN Channel: ",
      position: "Position [m]:",
      orie: "Orientation [deg]:",
      output_raw_vel: "Output raw velocity and acceleration"
  };
