var cn = {
  lidar1: "激光雷达1",
  lidar2: "激光雷达2",
  device: "设备",
  connect: "连接",
  ip_filter: "IP筛选器(可选):",
  adaptor: "适配器:",
  point_cloud_output_channel: "点云输出通道:",
  point_map_output_channel: "点阵输出通道:",
  processing: "处理",
  device_type: "设备类型:",
  frame_split_angle: "帧分割角[deg]:",
  origin: "原点 [m]:",
  yaw_offset: "偏航角偏移量[deg]:",
  for_only: "仅用于离线/回放模式",
  disabled: "(禁用)",
  channel_a: "通道 A",
  channel_b: "通道 B",
  channel_c: "通道 C"
},
en = {
  disabled: "(Disabled)",
  channel_a: "Channel A",
  channel_b: "Channel B",
  channel_c: "Channel C",
  for_only: "For offline/replay mode only",
  lidar1: "Lidar1",
  lidar2: "Lidar2",
  device: "Device",
  connect: "Connect",
  ip_filter: "IP filter (optional):",
  adaptor: "Adaptor:",
  device_type: "Device type:",
  frame_split_angle: "Frame split angle [deg]:",
  processing: "Processing",
  point_cloud_output_channel: "Point cloud output channel:",
  point_map_output_channel: "Point map output channel:",
  origin: "Origin [m]:",
  yaw_offset: "Yaw offset [deg]:"
};