var cn = {
  input: "输入",
  enabled: " 启用",
  processing: "处理",
  disabled: "(未启用)",
  out_channel: "目标物输出通道:",
  lane_channel: "车道线输出通道:",
  origin: "起始点 [m]:",
  pos_offset: "偏移位置[°]:",
  pitch: "倾斜度",
  roll: "旋转",
  yaw: "偏航",
  import_data: "导入数据",
  not_config: "<未配置>",
  result_path: "参考结果路径:",
  time_type: "时间类型:",
  road_edge_channel:"路沿输出通道:"
},
en = {
  enabled: " Enabled",
  input: "Input",
  processing: "Processing",
  disabled: "(Disabled)",
  out_channel: "Objects Output Channel:",
  lane_channel: "Lanes Output Channel:",
  origin: "Origin [m]:",
  pos_offset: "Pos Offset[°]:",
  pitch: "Pitch",
  roll: "Roll",
  yaw: "Yaw",
  import_data: "Import Data",
  not_config: "<Not Configured>",
  result_path: "Reference Result Path:",
  time_type: "Time Type:",
  road_edge_channel:"Road_edge Output Channel:"
};