var cn = {
  bus_devices: "总线设备列表",
  unnecessary: "无需配置",
  not_config: "<未配置>",
  message_bindings: "发送报文协议绑定",
  add_binding: "添加报文协议绑定",
  channel_protocols: "各通道协议文件",
  bus_information: "检查总线设备插件",
  info: "信息",
  sure: "确定",
  message: "报文:",
  del_message: "删除",
  counter_signal: "计数器信号:",
  validator_signal: "验证信号:",
  validator_type: "验证方式:",
  validation_parameters: "相关参数",
  crc8_parameters: "CRC8参数",
  inversion: "取反",
  origin: "初始值:",
  poly: "Poly:",
  type: "类型:",
  rate: "速率:",
  bit_rate_sub: "子速率:",
  channel: "软件通道:",
  add_channel_protocol: "添加",
  source_signal:"信号源:",
  default_val:"默认值:",
},
  en = {
    bus_devices: "Bus devices",
    unnecessary: "Unnecessary to configure",
    not_config: "<Not Configured>",
    message_bindings: "Message bindings",
    add_binding: "Add binding",
    channel_protocols: "Channel protocols",
    bus_information: "Check bus device plugins",
    info: "Infomation",
    sure: "Confirm",
    message: "Message:",
    del_message: "Delete",
    counter_signal: "Counter signal:",
    validator_signal: "Validator signal:",
    validator_type: "Validator type:",
    validation_parameters: "Validation parameters",
    crc8_parameters: "CRC8 Parameters",
    inversion: "Inversion",
    origin: "Origin:",
    poly: "Poly:",
    type: "",
    type: "Type:",
    rate: "Rate:",
    bit_rate_sub: "Arbit.:",
    channel: "Channel:",
    add_channel_protocol: "Add",
    source_signal:"Source signal:",
    default_val:"Default value:",
  };