var zh = {
  Enabled: "启动",
  exposure: "曝光:",
  shutter_time: "快门时间:",
  framerate: "帧率:",
  gain_count: "获取帧数:",
  white_balance_low: "白平衡低值:",
  white_balance_high: "白平衡高值:",
  jpeg_quality: "图像质量值:",
  image_type: "图像类型:",
  auto:"自动",
  manual:"手动",
},
  en = {
    Enabled: "Enabled",
    exposure: "Exposure:",
    shutter_time: "Shutter time:",
    framerate: "Framerate:",
    gain_count: "Gain count:",
    white_balance_low: "White balance low:",
    white_balance_high: "White balance high:",
    jpeg_quality: "JPEG quality:",
    image_type: "Image type:",
    auto:"Auto",
    manual:"Manual",
  };