var cn = {
    gnss_a: "GNSS-IMU设备A",
    gnss_b: "GNSS-IMU设备B",
    gnss_c: "GNSS-IMU设备C",
    gnss_d: "GNSS-IMU设备D",
    gnss_e: "GNSS-IMU设备E",
    gnss_f: "GNSS-IMU设备F",
    output_sample_version: "输出样本协议版本",
    enabled: "启用",
    channel: "输出通道: ",
    sampling_msg: "帧尾报文: ",
    gnss: "GNSS",
    longitude: "经度 [°E]:",
    latitude: "纬度 [°N]:",
    altitude: "海拔 [m]:",
    speed: "速度 [KPH]:",
    orientation_deg: "朝向角 [deg]:",
    orientation_offset: "朝向角偏置:",
    satellite_count: "卫星数量:",
    location_mode: "位置模式",
    locmode: "模式信号:",
    locmode_rtkfix: "RTK固定解枚举值:",
    locmode_rtkfloat: "RTK浮动解枚举值:",
    locmode_rtd: "RTD枚举值:",
    locmode_imuonly: "仅惯导枚举值:",
    hor_err: "水平位置误差[m]:",
    ver_err: "垂直位置误差[m]:",
    antenna: "天线",
    imu: "IMU",
    yaw_rate: "横摆角速度 [deg/s]:",
    pitch: "俯仰角 [deg]:",
    pitch_rate: "俯仰角速度 [deg/s]:",
    roll_rate: "横滚角速度[deg/s]:",
    roll: "横滚角 [deg]:",
    ax: "X轴加速度 [m/s2]:",
    ay: "Y轴加速度 [m/s2]:",
    az: "Z轴加速度 [m/s2]:",
    jerkx: "X轴急动度 [m/s3]:",
    jerky: "Y轴急动度 [m/s3]:",
    slip: "侧偏角 [deg]:",
    yaw_rate_offset: "横摆角速度偏置:",
    pitch_offset: "俯仰角偏置:",
    roll_offset: "横滚角偏置:",
    time: "时间",
    gps_time_mode: "时间模式:",
    disabled: "(未启用)",
    absolute: "独立数值",
    posix: "Posix时间",
    week: "日内或者周内时间",
    gps_time_year: "年:",
    gps_time_month: "月:",
    gps_time_week: "周:",
    gps_time_day: "天:",
    gps_time_hour: "时:",
    gps_time_minute: "分:",
    gps_time_second: "秒:",
    gps_time_ms: "毫秒:",
    import: "导入配置",
    export: "导出配置",
    gps_time_type: "时间类型:",
    scale_small: "比例: 小范围",
    scale_large: "比例: 大范围",
    lane_sensor: "Lane Sensor",
    not_config: "<未配置>"
  },
  en = {
    hor_err: "Horizontal err.[m]:",
    ver_err: "Vertical err.[m]:",
    scale_small: "Scale: Small",
    scale_large: "Scale: Large",
    gps_time_type: "Time type:",
    gnss_a: "GNSS-IMU Sensor A",
    gnss_b: "GNSS-IMU Sensor B",
    gnss_c: "GNSS-IMU Sensor C",
    gnss_d: "GNSS-IMU Sensor D",
    gnss_e: "GNSS-IMU Sensor E",
    gnss_f: "GNSS-IMU Sensor F",
    output_sample_version: "Output sample version:",
    enabled: "Enabled",
    channel: "Channel:",
    sampling_msg: "Final msg:",
    gnss: "GNSS",
    longitude: "Longitude [°E]:",
    latitude: "Latitude [°N]:",
    altitude: "Altitude [m]:",
    speed: "Speed [KPH]:",
    orientation_deg: "Orientation [deg]:",
    orientation_offset: "Orientation offset:",
    satellite_count: "Satellite count:",
    location_mode: "Location Mode",
    locmode: "Mode signal:",
    locmode_rtkfix: "RTK-fixed values:",
    locmode_rtkfloat: "RTK-float values:",
    locmode_rtd: "RTD values:",
    locmode_imuonly: "IMU-only values:",
    antenna: "Antenna",
    imu: "IMU",
    yaw_rate: "Yaw rate [deg/s]:",
    pitch: "Pitch angle [deg]:",
    roll: "Roll angle [deg]:",
    ax: "Accel-X [m/s2]:",
    ay: "Accel-Y [m/s2]:",
    az: "Accel-Z [m/s2]:",
    jerkx: "Jerk-X [m/s3]:",
    jerky: "Jerk-Y [m/s3]:",
    slip: "Slip angle [deg]:",
    yaw_rate_offset: "Yaw rate offset:",
    pitch_offset: "Pitch angle offset:",
    roll_offset: "Roll angle offset:",
    time: "Time",
    gps_time_mode: "Time mode:",
    disabled: "Disabled",
    absolute: "Absolute",
    posix: "Posix",
    week: "In-day / In-week",
    gps_time_year: "Year:",
    gps_time_month: "Month:",
    gps_time_week: "Week:",
    gps_time_day: "Day:",
    gps_time_hour: "Hour:",
    gps_time_minute: "Minute:",
    gps_time_second: "Second:",
    gps_time_ms: "Millisecond:",
    import: "Import",
    export: "Export",
    lane_sensor: "Lane Sensor",
    pitch_rate: "Pitch rate [deg/s]:",
    roll_rate: "Roll rate [deg/s]:",
    not_config: "<Not configured>"
  }