var zh = {
    Enabled: "启用",
    middleLidarIP: "中雷达IP:",
    leftLidarIP: "左雷达IP:",
    rightLidarIP: "右雷达IP:",
    gnssimuChannel: "组合惯导通道:",
    frontobjectChannel: "前向目标物通道:",
    rearobjectChannel: "后向目标物通道:",
    frameSplitAngle: "分割角度[度]:",
    syncTimeOffset: "Sync时间偏移[秒]:",
    RosType: "Ros类型:",
    timeSourceOffset:"时间源差值[毫秒]:",
    lidarBagType:"Bag类型:",
    completeframes:"完整帧数",
    completepackets:"完整包数",
    lidarIP:"雷达IP",
    typeandangle:"类型和角度",
    sample:"样本",
    frontLidarIP:"前雷达IP:",
    rearLidarIP:"后雷达IP:",
    bpearlTimeType:"Bpearl时间类型:"
  },
  en = {
    Enabled: "Enabled",
    middleLidarIP: "Middle lidar IP:",
    leftLidarIP: "Left lidar IP:",
    rightLidarIP: "Right lidar IP:",
    gnssimuChannel: "GNSS-IMU channel:",
    frontobjectChannel: "Front object channel:",
    rearobjectChannel: "Rear object channel:",
    frameSplitAngle: "Split angle [°]:",
    syncTimeOffset: "Sync time offset [s]:",
    RosType: "Ros type:",
    timeSourceOffset:"Time source offset [ms]:",
    lidarBagType:"Bag type:",
    completeframes:"Complete Frames",
    completepackets:"Complete Packets",
    lidarIP:" Lidar IP",
    typeandangle:"Type And Angle",
    sample:"Sample",
    frontLidarIP:"Front lidar IP:",
    rearLidarIP:"Rear lidar IP:",
    bpearlTimeType:"Bpearl time type:"
  };