var zh = {
  input_chan: "输入通道:",
  output_channel: "输出通道:",
  frequency: "输出频率[Hz]:",
  acti_at_least: "激活至少2个通道来启用",
  out_mode: "输出模式",
  fusion_distance: "融合距离[m]:",
  close_point: "最近点",
  box_center: "框中心",
  separation_distance: "分离距离[m]:",
  obj_exis: "目标物存在权重",
  classification_weight: "目标物类型权重",
  size_weight: "目标物尺寸/朝向权重",
  pos_weight: "目标物位置权重",
  velocity_weight: "目标物速度/加速度权重",
  none: "0%",
  half: "50%",
  full: "100%",
  obj_a: "目标物传感器 A",
  obj_b: "目标物传感器 B",
  obj_c: "目标物传感器 C",
  obj_d: "目标物传感器 D",
  obj_e: "目标物传感器 E",
  obj_f: "目标物传感器 F",
  obj_g: "目标物传感器 G",
  obj_h: "目标物传感器 H",
  obj_i: "目标物传感器 I",
  obj_j: "目标物传感器 J",
  obj_k: "目标物传感器 K",
  obj_l: "目标物传感器 L",
  disabled: "禁用",
},
  en = {
    disabled: "Disabled",
    obj_a: "Object sensor A",
    obj_b: "Object sensor B",
    obj_c: "Object sensor C",
    obj_d: "Object sensor D",
    obj_e: "Object sensor E",
    obj_f: "Object sensor F",
    obj_g: "Object sensor G",
    obj_h: "Object sensor H",
    obj_i: "Object sensor I",
    obj_j: "Object sensor J",
    obj_k: "Object sensor K",
    obj_l: "Object sensor L",
    none: "0%",
    half: "50%",
    full: "100%",
    out_mode: "Output Mode",
    acti_at_least: "Activate at least 2 channels to enable",
    input_chan: "Input Channels:",
    output_channel: "Output Channel:",
    frequency: "Output Frequency[Hz]:",
    fusion_distance: "Fusion Distance[m]:",
    close_point: "Closest Point",
    box_center: "Box Center",
    separation_distance: "Separation Distance[m]:",
    obj_exis: "Object Existance",
    classification_weight: "Classification Weight",
    pos_weight: "Position Weight",
    velocity_weight: "Velocity/Acceleration Weight",
    size_weight: 'Size/Heading Weight'
  };