var cn = {
  enabled: "启用（仅在线模式工作）",
  location_source: "通道:",
  data: "数据",
  weather: "天气",
  air: "空气质量",
  alarm: "天气预警",
  moon: "月球数据",
  sun: "太阳数据",
  driving_restriction: "交通状况",
  road_condition: "出行限号",
  location_source_0: "组合惯导通道A",
  location_source_1: "组合惯导通道B",
  location_source_2: "组合惯导通道C",
  location_source_3: "组合惯导通道D",
  location_source_4: "组合惯导通道E",
  location_source_5: "组合惯导通道F"
},
  en = {
    enabled: "Enable ( Only work at online mode)",
    location_source: "Channel:",
    data: "Data",
    weather: "Weather",
    air: "Air",
    alarm: "Alarm",
    moon: "Moon",
    sun: "Sun",
    driving_restriction: "Road Condition",
    road_condition: "Driving Restriction",
    location_source_0: "GNSS-IMU Channel A",
    location_source_1: "GNSS-IMU Channel B",
    location_source_2: "GNSS-IMU Channel C",
    location_source_3: "GNSS-IMU Channel D",
    location_source_4: "GNSS-IMU Channel E",
    location_source_5: "GNSS-IMU Channel F"
  };