let cn = {
        title_option: "默认标题选项:",
        prefix: "前缀名",
        message_name: "报文名",
        enabled: "启用",
        add_park: "添加一个信号打包样本",
        interpolation_mode: "插值模式 采样频率[Hz]:",
        raw_mode: "原始数据模式 帧尾报文:",
        not_config: "<未配置>",
        add_signal: "添加信号",
        add_msg: "批量添加报文信号",
        title: "标题:",
        timeout: "超时[毫秒]:",
        interpolation: "插值:",
        signal: "信号:",
        enabled_with: "启用 打包样本协议名: ",
        linear: "线性",
        nearest: "最近",
        packing_signal: "打包信号列表",
    },
    en = {
        title_option: "Title option:",
        prefix: "Prefix",
        message_name: "Message name",
        linear: "Nearest",
        nearest: "Linear",
        enabled: "Enabled",
        add_park: "Add a packing",
        interpolation_mode: "Interpolation mode @ sampling rate [Hz]:",
        raw_mode: "Raw mode with final msg:",
        not_config: "<Not Configured>",
        add_signal: "Add signal",
        add_msg: "Add message's signals",
        title: "Title:",
        timeout: "Timeout [ms]:",
        interpolation: "Interpolation:",
        signal: "Signal:",
        enabled_with: "Enabled with protocol ID: ",
        packing_signal: "Packing signal:",
    };