var cn = {
  connect: "连接",
  com_port: "COM端口号:",
  com_baud_rate: "COM端口波特率:",
  output_channel: "输出通道:",
  device_part: "设备",
  device_type: "设备类型:",
  processing_part: "处理",
  b48: "4800 波特",
  b96: "9600 波特",
  b192: "19200 波特",
  b384: "38400 波特",
  b576: "57600 波特",
  b1152: "115200 波特",
  b2304: "230400 波特",
  b4608: "460800 波特",
  disabled: "(禁用)",
  gnss_imu_a: "GNSS-IMU 传感器 A",
  gnss_imu_b: "GNSS-IMU 传感器 B",
  gnss_imu_c: "GNSS-IMU 传感器 C",
  gnss_imu_d: "GNSS-IMU 传感器 D",
  gnss_imu_e: "GNSS-IMU 传感器 E",
  gnss_imu_f: "GNSS-IMU 传感器 F",
  pitch_angle_offset: "俯仰角偏移:",
  roll_angle_offset: "横滚角偏移:",
  novatel_imu_type:"诺瓦泰IMU型:",
  time_type:"时间类型:",
  orientation_offset:"方向偏移:",
  pos:"天线位置(m):",
  connect_gps_comm:"连接GPS COM端口",
  send_command:"发送指令",
  com2_port:"COM2端口号:",
  connect_comm:"连接指令:",
  GnssTimeType:"惯导时间类型:",
  posixtime:"Posix时间",
  Localtime:"北京时间"
},
  en = {
      b48: "4800 Baud",
      b96: "9600 Baud",
      b192: "19200 Baud",
      b384: "38400 Baud",
      b576: "57600 Baud",
      b1152: "115200 Baud",
      b2304: "230400 Baud",
      b4608: "460800 Baud",
      disabled: "(Disabled)",
      gnss_imu_a: "GNSS-IMU Sensor A",
      gnss_imu_b: "GNSS-IMU Sensor B",
      gnss_imu_c: "GNSS-IMU Sensor C",
      gnss_imu_d: "GNSS-IMU Sensor D",
      gnss_imu_e: "GNSS-IMU Sensor E",
      gnss_imu_f: "GNSS-IMU Sensor F",
      connect: "Connect",
      com_port: "COM port:",
      com2_port:"COM2 port:",
      com_baud_rate: "COM baud rate:",
      output_channel: "Output channel:",
      device_part: "Device",
      device_type:"Device type:",
      processing_part: "Processing",
      pitch_angle_offset: "Pitch angle offset:",
      roll_angle_offset: "Roll angle offset:",
      novatel_imu_type:"Novatel IMU type:",
      time_type:"Time type:",
      orientation_offset:"Orientation offset:",
      pos:"Antenna positon(m):",
      connect_gps_comm:"Connect GPS Comm",
      send_command:"Send command",
      connect_comm:"Connect command:",
      GnssTimeType:"GNSS time type:",
      posixtime:"Posix time",
      Localtime:"Local time"
  };