var cn = {
  enable: "Enable",
  enableCanFD: "EnabledCanFD",
  canBitrate: "bitrate:",
  canFDBitrate: "fdbitrate:",
  videoResolution: "VideoResolution:",
  rawFormat: "RawFormat:",
  smallCodec: "SmallCodec:",
  bus_channel: "Bus channel:",
  bus_msgid: "Message ID:",
  server_ip: "Dst IP:",
  server_port_num: "Dst Port:",
  bus: "Bus",
  video: "Video",
  ethernet: "Ethernet",
  video_channel: "Video channel:",
  busDeviceType:"Device type:",
  local_ip:"Local IP:",
  local_port_num:"Local Port:"
},
  en = {
    enable: "Enable",
    enableCanFD: "EnabledCanFD",
    canBitrate: "bitrate:",
    canFDBitrate: "fdbitrate:",
    videoResolution: "VideoResolution:",
    rawFormat: "RawFormat:",
    smallCodec: "SmallCodec:",
    bus_channel: "Bus channel:",
    bus_msgid: "Message ID:",
    server_ip: "Dst IP:",
    server_port_num: "Dst Port:",
    bus: "Bus",
    video: "Video",
    ethernet: "Ethernet",
    video_channel: "Video channel:",
    busDeviceType:"Device type:",
    local_ip:"Local IP:",
    local_port_num:"Local Port:"
  };