var cn = {
  write_option: "写入选项",
  binary_data: "原始二进制数据",
  bus: "总线原始数据",
  video: "视频原始数据",
  audio: "音频原始数据",
  signal_data: "信号数据",
  bus_data: "总线信号",
  sample_data: "样本数据",
  matrix_data: "矩阵数据",
  online_mode: "在线模式",
  offline_mode: "离线模式",
  enabled: "启用",
  not_available: "不可用",
  read_option: "读取选项",
  from_raw_data: "来自原始数据",
  from_generation: "来自generation",
  replay_mode: "回放模式",
  disabled_all: "全部禁用",
  reset_to_default: "恢复默认",
  bus_record_format: "记录总线文件格式",
  mixed_ascii: "混合类型的ASC码记录文件(asc)",
  multiple_ascii: "多通道的ASC码记录文件(asc)",
  single_ascii: "单通道的ASC码记录文件(asc)",
  mixed_binary: "混合类型的二进制记录文件(blf)",
  multiple_binary: "多通道的二进制记录文件(blf)",
  single_binary: "单通道的二进制记录文件(blf)",
  multiple_encrypted: "多通道的加密记录文件(ebd)",
  single_encrypted: "单通道的加密记录文件(ebd)",
  small: "小片段(每文件6分钟)",
  mixed_ascii_6min: "混合类型的ASC码记录文件(每文件6分钟)",
  mixed_binary_6min: "混合类型的二进制记录文件(每文件6分钟)",
  single_pcap: "单通道的PCAP文件(pcap)",
  file_type: "采集文件格式",
  file_pos: "采集文件位置",
  avi_file: "AVI 文件",
  mp4_file: "MP4 文件",
  mkv_file: "MKV 文件",
  dat_file: "DAT 文件",
  main_data_path: "主数据目录",
  video_record_config: "视频记录配置",
  data_password: "数据加密/解密密码配置",
  password: "密码:",
  unlock: "解锁",
  show: "显示",
  data_encryption: "数据加密/解密配置",
  audio_config: "音频记录配置",
  quality: "质量:",
  normal: "一般",
  high: "高",
  record_legacy_style: "按旧方式记录文件"
},
  en = {
    write_option: "Write option",
    binary_data: "Raw binary data",
    bus: "Bus raw data",
    video: "Video raw data",
    audio: "Audio raw data",
    signal_data: "Signal data",
    bus_data: "Bus signals",
    sample_data: "Sample data",
    matrix_data: "Matrix data",
    online_mode: "Online mode",
    offline_mode: "Offline mode",
    enabled: "Enabled",
    not_available: "Not available",
    read_option: "Read option",
    from_raw_data: "From raw data",
    from_generation: "From generation",
    replay_mode: "Replay mode",
    disabled_all: "Disable all",
    reset_to_default: "Reset to default",
    bus_record_format: "Bus Record Format",
    mixed_ascii: "Mixed type ASCII logging file (asc)",
    multiple_ascii: "Multiple channel ASCII logging File(asc)",
    single_ascii: "Single channel ASCII logging file (asc)",
    mixed_binary: "Mixed type binary logging file (blf)",
    multiple_binary: "Multiple type binary logging file (blf)",
    single_binary: "Single channel binary logging file(blf)",
    multiple_encrypted: "Multiple channel encrypted file(ebd)",
    single_encrypted: "Single channel encrypted file(ebd)",
    small: "Small segments (6min/file)",
    mixed_ascii_6min: "Mixed type ASCII logging file (6min/file)",
    mixed_binary_6min: "Mixed type binary logging file (6min/file)",
    single_pcap: "Single channel PCAP file (pcap)",
    file_type: "Record File Format",
    file_pos: "Record File Location",
    avi_file: "AVI File",
    mp4_file: "MP4 File",
    mkv_file: "MKV File",
    dat_file: "DAT File",
    main_data_path: "Main Data Path",
    video_record_config: "Video Record Config",
    data_password: "Data encryption/decryption password",
    password: "Password:",
    unlock: "Unlock",
    show: "Show password",
    data_encryption: "Data encryption key",
    audio_config: "Audio Record Config",
    quality: "Quality:",
    normal: "Normal",
    high: "High",
    record_legacy_style: "Record as legacy style"
  };