var cn = {
  hdmap_source: "HDMap 源",
  external_shp: "全局的(shp)",
  external_xoder: "全局的(xodr)",
  ppbgis: "用gnss imu样品后处理(map-gis.xodr)",
  ppblss: "lane sensor样本后处理(map-lss.xodr)",
  none: "无",
  process: "处理",
  gnss_imu_input_channel: "GNSS-IMU输入通道:",
  lane_out_channel: "车道线输出通道:",
  for_exten: "向前延伸[米]:",
  baskr_exten: "向后扩展[米]:",
  coatse_inter: "Coarse间隔[米]:",
  fine_inter: "Fine间隔[米]:",
  signal_out: "信号输出",
  lane_id: "线 ID:",
  signal: "信号:",
  not_config: "<未配置>",
  description: "描述:",
  add: "添加",
  clear: "清空",
  empty: "<无>",
  lane_sensor_a: "车道线传感器 A",
  lane_sensor_b: "车道线传感器 B",
  lane_sensor_c: "车道线传感器 C",
  lane_sensor_d: "车道线传感器 D",
  lane_sensor_e: "车道线传感器 E",
  lane_sensor_f: "车道线传感器 F",
  lane_sensor_g: "车道线传感器 G",
  lane_sensor_h: "车道线传感器 H",
  disabled: "(禁用)",
},
  en = {
    lane_sensor_a: "Lane sensor A",
    lane_sensor_b: "Lane sensor B",
    lane_sensor_c: "Lane sensor C",
    lane_sensor_d: "Lane sensor D",
    lane_sensor_e: "Lane sensor E",
    lane_sensor_f: "Lane sensor F",
    lane_sensor_g: "Lane sensor G",
    lane_sensor_h: "Lane sensor H",
    disabled: "(Disabled)",
    empty: "<Empty>",
    hdmap_source: "HDMap Source",
    external_shp: "External(shp)",
    external_xoder: "External(xodr)",
    ppbgis: "Post processed by gnss imu sample (map-gis.xodr)",
    ppblss: "Post processed by lane sensor sample (map-lss.xodr)",
    none: "None",
    process: "Processing",
    gnss_imu_input_channel: "GNSS-IMU input channel:",
    lane_out_channel: "Lanes output channel:",
    for_exten: "Forward extension [m]:",
    baskr_exten: "Backward extension [m]:",
    coatse_inter: "Coarse interval [m]:",
    fine_inter: "Fine interval [m]:",
    signal_out: "Signals Output",
    lane_id: "Lane id:",
    signal: "Signal:",
    not_config: "<Not Configured>",
    description: "Description:",
    add: "Add",
    clear: "Clear",
  };