var en = {
    process_tool: "IDC Processing Tool",
    outputs: "Outputs:",
    vehicle_state: "Vehicle State",
    objects: "Objects:",
    coordination: "Coordination:",
    origin: "Origin [m]:",
    yam_offset: "Yaw offset [°]:",
    data_source: "Data source:",
    ex_file: "Executable File:",
    invalid: "Invalid",
    evs_process: "EVS Process",
    parse: "Parse",
    primary: "(Primary)",
    secondary: "(Secondary)",
    processed: "Processed",
    arrival_time: "Arrival Time",
    sync_csv: "Sync CSV",
    ptp_sync: "PTP Sync",
    gnss_sync: "GNSS Sync",
    parse_idc: "Parsed IDC",
    manager: "Manager",
    del_all: "Delete All",
    ses_manager: "Session Manager",
    load: "Load",
    clear: "Clear",
    default: "Default",
    ok: "OK",
    cancel: "Cancel",
    obj_a: "Object Sensor A",
    obj_b: "Object Sensor B",
    obj_c: "Object Sensor C",
    obj_d: "Object Sensor D",
    obj_e: "Object Sensor E",
    obj_f: "Object Sensor F",
    obj_g: "Object Sensor G",
    obj_h: "Object Sensor H",
    obj_i: "Object Sensor I",
    obj_j: "Object Sensor J",
    obj_k: "Object Sensor K",
    obj_l: "Object Sensor L",
    disabled: "(Disabled)",
    processLanes:"Process lanes",
    lanes:"Lanes:",
    lane_sensor_a: "Lane Sensor A",
    lane_sensor_b: "Lane Sensor B",
    lane_sensor_c: "Lane Sensor C",
    lane_sensor_d: "Lane Sensor D",
    lane_sensor_e: "Lane Sensor E",
    lane_sensor_f: "Lane Sensor F",
    lane_sensor_g: "Lane Sensor G",
    lane_sensor_h: "Lane Sensor H",
    lane_sensor_i: "Lane Sensor I",
    lane_sensor_j: "Lane Sensor J",
    lane_sensor_k: "Lane Sensor K",
    lane_sensor_l: "Lane Sensor L",
  },
  cn = {
    disabled: "(禁用)",
    obj_a: "目标物通道A",
    obj_b: "目标物通道B",
    obj_c: "目标物通道C",
    obj_d: "目标物通道D",
    obj_e: "目标物通道E",
    obj_f: "目标物通道F",
    obj_g: "目标物通道G",
    obj_h: "目标物通道H",
    obj_i: "目标物通道I",
    obj_j: "目标物通道J",
    obj_k: "目标物通道K",
    obj_l: "目标物通道L",
    data_source: "数据源:",
    process_tool: "IDC处理工具",
    outputs: "样本输出:",
    vehicle_state: "输出车辆状态",
    objects: "目标物",
    coordination: "坐标系:",
    origin: "原点 [m]:",
    yam_offset: "偏航角偏移[°]:",
    ex_file: "可执行文件:",
    invalid: "无效",
    evs_process: "EVS处理",
    parse: "解析",
    primary: "(初级)",
    secondary: "(中级)",
    processed: "处理",
    arrival_time: "到达时间",
    sync_csv: "同步CSV",
    ptp_sync: "PTP同步",
    gnss_sync: "GNSS同步",
    parse_idc: "解析IDC",
    manager: "管理",
    del_all: "删除所有",
    ses_manager: "Session管理",
    load: "导入",
    clear: "清除",
    default: "默认",
    ok: "确定",
    cancel: "取消",
    processLanes:"处理车道线",
    lanes:"车道线:",
    lane_sensor_a: "车道线传感器A",
    lane_sensor_b: "车道线传感器B",
    lane_sensor_c: "车道线传感器C",
    lane_sensor_d: "车道线传感器D",
    lane_sensor_e: "车道线传感器E",
    lane_sensor_f: "车道线传感器F",
    lane_sensor_g: "车道线传感器G",
    lane_sensor_h: "车道线传感器H",
    lane_sensor_i: "车道线传感器I",
    lane_sensor_j: "车道线传感器J",
    lane_sensor_k: "车道线传感器K",
    lane_sensor_l: "车道线传感器L",
  }