var cn = {
  in_point_map: "输入点阵图:",
  no1: "第一",
  output_obj: "输出目标物:",
  output_free: "输出可行驶区域:",
  no2: "第二",
  param: "参数",
  min_point_dist: "最小值点的距离",
  max_relat_speed: "最大相对速度",
  max_lat_clear: "最大侧隙",
  disabled: "(禁用)",
  chan_a: "通道 A",
  chan_b: "通道 B",
  chan_c: "通道 C",
  chan_d: "通道 D",
  chan_e: "通道 E",
  chan_f: "通道 F",
  chan_g: "通道 G",
  chan_h: "通道 H",
  chan_i: "通道 I",
  chan_j: "通道 J",
  chan_k: "通道 K",
  chan_l: "通道 L",
},
en = {
  disabled: "(Disabled)",
  chan_a: "Channel A",
  chan_b: "Channel B",
  chan_c: "Channel C",
  chan_d: "Channel D",
  chan_e: "Channel E",
  chan_f: "Channel F",
  chan_g: "Channel G",
  chan_h: "Channel H",
  chan_i: "Channel I",
  chan_j: "Channel J",
  chan_k: "Channel K",
  chan_l: "Channel L",
  in_point_map: "Input point map:",
  no1: "1st",
  output_obj: "Output objects:",
  output_free: "Output Freespace:",
  no2: "2nd",
  param: "Parameters",
  min_point_dist: "Minimum point distance",
  max_relat_speed: "Maximum relative speed",
  max_lat_clear: "Maximum lateral clearance",
};