var zh = {
    enable: "启用",
    video_data_channel: "视频数据通道:",
    video_target_channel: "视频目标通道:",
    bus_target_channel: "总线目标通道:",
    bus_data_channel: "总线数据通道:",
    bus_msgid: "报文ID:",
    ethernet: "以太网",
    bus: "总线",
    video: "视频",
    protocolName: "协议名:",
    general: "通用",
    transmit_mode: "发送模式:",
    server_posix_offset: "预约发送时间偏置:",
    packet_loss_rate: "丢包率:",
    cutoff_start_time: "断流起始时间点:",
    cutoff_time_length: "断流的时间长度:",
    port: "Src端口号:",
    realTimeThread:"实时线程"
  },
  en = {
    enable: "Enabled",
    video_data_channel: "Video data channel:",
    video_target_channel: "Target video channel:",
    bus_target_channel: "Target bus channel:",
    bus_data_channel: "Bus data channel:",
    bus_msgid: "Message ID:",
    ethernet: "Ethernet",
    bus: "Bus",
    video: "Video",
    protocolName: "Protocol name:",
    general: "General",
    transmit_mode: "Transmit mode:",
    server_posix_offset: "Server posix offset:",
    packet_loss_rate: "Packet loss rate:",
    cutoff_start_time: "Cutoff start time:",
    cutoff_time_length: "Cutoff time length:",
    port: "Src Port:",
    realTimeThread:"Real time thread"
  };