var cn = {
    enable: "启用",
    enableCanFD: "EnabledCanFD",
    canBitrate: "bitrate:",
    canFDBitrate: "fdbitrate:",
    videoResolution: "VideoResolution:",
    rawFormat: "RawFormat:",
    smallCodec: "SmallCodec:",
    bus_channel: "Bus channel:",
    bus_msgid: "Message ID:",
    server_ip: "目标IP:",
    server_port_num: "目标端口号:",
    bus: "Bus",
    video: "Video",
    ethernet: "以太网",
    video_channel: "Video channel:",
    busDeviceType: "Device type:",
    local_ip: "本地IP:",
    local_port_num: "本地端口号:",
    data_offset: "数据偏移:",
    transmit_mode: "发送模式:",
    Instantaneous: "瞬时",
    Scheduled: "预约"
  },
  en = {
    enable: "Enable",
    enableCanFD: "EnabledCanFD",
    canBitrate: "bitrate:",
    canFDBitrate: "fdbitrate:",
    videoResolution: "VideoResolution:",
    rawFormat: "RawFormat:",
    smallCodec: "SmallCodec:",
    bus_channel: "Bus channel:",
    bus_msgid: "Message ID:",
    server_ip: "Dst IP:",
    server_port_num: "Dst Port:",
    bus: "Bus",
    video: "Video",
    ethernet: "Ethernet",
    video_channel: "Video channel:",
    busDeviceType: "Device type:",
    local_ip: "Local IP:",
    local_port_num: "Local Port:",
    data_offset: "Data Offset:",
    transmit_mode: "Transmit Mode:",
    Instantaneous: "Instantaneous",
    Scheduled: "Scheduled"
  };