let cn = {
  enable: '启动',
  dev1_bus_channel: "Dev1总线通道:",
  dev1_bus_message_id: "Dev1总线信息ID:",
  dev2_bus_channel: "Dev2总线通道:",
  dev2_bus_message_id: "Dev2总线信息ID:",
  dev3_bus_channel: "Dev3总线通道:",
  dev3_bus_message_id: "Dev3总线信息ID:",
  dev4_bus_channel: "Dev4总线通道:",
  dev4_bus_message_id: "Dev4总线信息ID:",
  dev5_bus_channel: "Dev5总线通道:",
  dev5_bus_message_id: "Dev5总线信息ID:",
  dev6_bus_channel: "Dev6总线通道:",
  dev6_bus_message_id: "Dev6总线信息ID:",
},
en = {
  enable: "Enable",
  dev1_bus_channel: "Dev1 Bus channel:",
  dev1_bus_message_id: "Dev1 Message ID:",
  dev2_bus_channel: "Dev2 Bus channel:",
  dev2_bus_message_id: "Dev2 Message ID:",
  dev3_bus_channel: "Dev3 Bus channel:",
  dev3_bus_message_id: "Dev3 Message ID:",
  dev4_bus_channel: "Dev4 Bus channel:",
  dev4_bus_message_id: "Dev4 Message ID:",
  dev5_bus_channel: "Dev5 Bus channel:",
  dev5_bus_message_id: "Dev5 Message ID:",
  dev6_bus_channel: "Dev6 Bus channel:",
  dev6_bus_message_id: "Dev6 Message ID:",
};