var zh = {
  not_config: "<Empty>",
  referenceEnable: "Enable",
  detectionVideoChannel: "Detection camera:",
  confidenceThresh: "Confidence thresh:",
  nmsThresh: "NMS thresh:",
  objectThresh: "Object thresh:",
  detectionArea: "Detection area:",
  modelPath: "Model path:",
  classNamesPath: "Class names path:",
  usingCUDA: "Using CUDA:",
  imageWidth: "Input image width:",
  imageHeight: "Input image height:",
  distanceThresh: "Distance thresh:",
  minContourSize: "Min contour size:",
  outputBatch: "Output batch:",
  outputWidth: "Output width:",
  outputHeight: "Output height:",
  borderWidth:"Border width:",
  borderHeight:"Border height:",
  maxRectangleWidth:"Max rectangle width:",
  maxRectangleHeight:"Max rectangle height:",
  inputPath:'Input path:',
  confirm:"Yolo Reference",
  mosaicProcess:"Mosaic process:",
},
  en = {
    not_config: "<Empty>",
    referenceEnable: "Enable",
    detectionVideoChannel: "Detection camera:",
    confidenceThresh: "Confidence thresh:",
    nmsThresh: "NMS thresh:",
    objectThresh: "Object thresh:",
    detectionArea: "Detection area:",
    modelPath: "Model path:",
    classNamesPath: "Class names path:",
    usingCUDA: "Using CUDA:",
    imageWidth: "Input image width:",
    imageHeight: "Input image height:",
    distanceThresh: "Distance thresh:",
    minContourSize: "Min contour size:",
    outputBatch: "Output batch:",
    outputWidth: "Output width:",
    outputHeight: "Output height:",
    borderWidth:"Border width:",
    borderHeight:"Border height:",
    maxRectangleWidth:"Max rectangle width:",
    maxRectangleHeight:"Max rectangle height:",
    inputPath:'Input path:',
    confirm:"Yolo Reference",
    mosaicProcess:"Mosaic process:",
  };