var zh = {
  enable: "启动",
  sync_fre: "输出频率[Hz]:",
  ori_offset: "朝向偏移[°]:",
  obj_channel: "目标物通道:",
  gps_channel: "组合惯导通道:",
  obj_chan_a: "目标物通道 A",
  obj_chan_b: "目标物通道 B",
  obj_chan_c: "目标物通道 C",
  obj_chan_d: "目标物通道 D",
  obj_chan_e: "目标物通道 E",
  obj_chan_f: "目标物通道 F",
  obj_chan_g: "目标物通道 G",
  obj_chan_h: "目标物通道 H",
  obj_chan_i: "目标物通道 I",
  obj_chan_j: "目标物通道 J",
  obj_chan_k: "目标物通道 K",
  obj_chan_l: "目标物通道 L",
  gnss_a: "组合惯导通道 A",
  gnss_b: "组合惯导通道 B",
  gnss_c: "组合惯导通道 C",
  gnss_d: "组合惯导通道 D",
  gnss_e: "组合惯导通道 E",
  gnss_f: "组合惯导通道 F",
  disabled: "(禁用)",
},
  en = {
    enable: "Enable",
    sync_fre: "Sync frequency [Hz]:",
    ori_offset: "Orientation offset [°]:",
    obj_channel: "Object channel:",
    gps_channel: "GPSIMU channel:",
    obj_chan_a: "Object channel A",
    obj_chan_b: "Object channel B",
    obj_chan_c: "Object channel C",
    obj_chan_d: "Object channel D",
    obj_chan_e: "Object channel E",
    obj_chan_f: "Object channel F",
    obj_chan_g: "Object channel G",
    obj_chan_h: "Object channel H",
    obj_chan_i: "Object channel I",
    obj_chan_j: "Object channel J",
    obj_chan_k: "Object channel K",
    obj_chan_l: "Object channel L",
    gnss_a: "GNSS-IMU channel A",
    gnss_b: "GNSS-IMU channel B",
    gnss_c: "GNSS-IMU channel C",
    gnss_d: "GNSS-IMU channel D",
    gnss_e: "GNSS-IMU channel E",
    gnss_f: "GNSS-IMU channel F",
    disabled: "(Disabled)",
  };