let cn = {
  output: "输出",
  input: "输入",
  processing: "处理",
  configure: "配置目标参数",
  sub: "主车参数",
  cal: "校正角计算",
  angle: "角",
  busChannel: "主车通道:",
  targetBusChannel: "目标1总线通道:",
  target1BusChannel: "目标2总线通道:",
  target2BusChannel: "目标3总线通道:",
  target3BusChannel: "目标4总线通道:",
  target4BusChannel: "目标5总线通道:",
  subMsgID: "主车报文ID:",
  targetMsgID: "目标1报文ID:",
  target1MsgID: "目标2报文ID:",
  target2MsgID: "目标3报文ID:",
  target3MsgID: "目标4报文ID:",
  target4MsgID: "目标5报文ID:",
  enabled: "启用",
  subGnssImuChannel: "主车GNSS-IMU通道:",
  targetGnssImuChannel: "目标1 GNSS-IMU通道:",
  target1GnssImuChannel: "目标2 GNSS-IMU通道:",
  target2GnssImuChannel: "目标3 GNSS-IMU通道:",
  target3GnssImuChannel: "目标4 GNSS-IMU通道:",
  target4GnssImuChannel: "目标5 GNSS-IMU通道:",
  //弹窗部分
  target1parameters: "目标参数1",
  target2parameters: "目标参数2",
  target3parameters: "目标参数3",
  target4parameters: "目标参数4",
  target5parameters: "目标参数5",
  origin_x: "起始位置X:",
  origin_y: "起始位置Y:",
  origin_z: "起始位置Z:",
  origin_offset: "朝向偏移:"
},
en = {
  output: "Output",
  input: "Input",
  processing: "Processing",
  configure: "Configure Target Parameters",
  sub: "Subject Parameters",
  cal: "Cal Correction Angle",
  angle: "Angle",
  busChannel: "SubBus Channel:",
  targetBusChannel: "Target1Bus Channel:",
  target1BusChannel: "Target2Bus Channel:",
  target2BusChannel: "Target3Bus Channel:",
  target3BusChannel: "Target4Bus Channel:",
  target4BusChannel: "Target5Bus Channel:",
  subMsgID: "Subject Message ID:",
  targetMsgID: "Target1 Message ID:",
  target1MsgID: "Target2 Message ID:",
  target2MsgID: "Target3 Message ID:",
  target3MsgID: "Target4 Message ID:",
  target4MsgID: "Target5 Message ID:",
  enabled: "Enabled",
  subGnssImuChannel: "Subject GNSS-IMU Channel:",
  targetGnssImuChannel: "Target1 GNSS-IMU Channel:",
  target1GnssImuChannel: "Target2 GNSS-IMU Channel:",
  target2GnssImuChannel: "Target3 GNSS-IMU Channel:",
  target3GnssImuChannel: "Target4 GNSS-IMU Channel:",
  target4GnssImuChannel: "Target5 GNSS-IMU Channel:",
  target1parameters: "Target1 Parameters",
  target2parameters: "Target2 Parameters",
  target3parameters: "Target3 Parameters",
  target4parameters: "Target4 Parameters",
  target5parameters: "Target5 Parameters",
  origin_x: "Origin Position X:",
  origin_y: "Origin Position Y:",
  origin_z: "Origin Position Z:",
  origin_offset: "Oritentation offset:"
};