var cn = {
    enable: "启动",
    connect: "连接",
    primary: "首要",
    secondary: "次要",
    how_to_lux: "如何配置lux",
    device: "设备",
    device_part: "设备部分",
    processing_part: "处理部分",
    address: "地址:",
    port: "端口:",
    import: "导入点云数据",
    record: "保存IDC文件",
    vehicle_sample: "输出车辆样本",
    only_support: "(只支持版本4.0以上的插件采集的数据)",
    without_object: "无后处理目标物输出通道:",
    with_object: "有后处理目标物输出通道:",
    without: "无后处理",
    with: "有后处理",
    signal_output: "信号输出:",
    origin: "原点 [米]:",
    yam_offset: "偏航角偏移[°]",
    point_output: "点云输出通道:",
    merge2: "融合两帧点云(针对lux 8L连接ECU的情况)",
    time_sync: "时间同步方式:",
    arrival_time: "到达时间",
    ntp_local_time: "NTP本地时间",
    disabled: "(禁用)",
    obj_sensor_a: "目标物传感器 A",
    obj_sensor_b: "目标物传感器 B",
    obj_sensor_c: "目标物传感器 C",
    obj_sensor_d: "目标物传感器 D",
    obj_sensor_e: "目标物传感器 E",
    obj_sensor_f: "目标物传感器 F",
    obj_sensor_g: "目标物传感器 G",
    obj_sensor_h: "目标物传感器 H",
    obj_sensor_i: "目标物传感器 I",
    obj_sensor_j: "目标物传感器 J",
    obj_sensor_k: "目标物传感器 K",
    obj_sensor_l: "目标物传感器 L",
    chan_a: "通道 A",
    chan_b: "通道 B",
    chan_c: "通道 C",
    chan_d: "通道 D",
    chan_e: "通道 E",
    chan_f: "通道 F",
  },
  en = {
    chan_a: "Channel A",
    chan_b: "Channel B",
    chan_c: "Channel C",
    chan_d: "Channel D",
    chan_e: "Channel E",
    chan_f: "Channel F",
    disabled: "(Disabled)",
    obj_sensor_a: "Object Sensor A",
    obj_sensor_b: "Object Sensor B",
    obj_sensor_c: "Object Sensor C",
    obj_sensor_d: "Object Sensor D",
    obj_sensor_e: "Object Sensor E",
    obj_sensor_f: "Object Sensor F",
    obj_sensor_g: "Object Sensor G",
    obj_sensor_h: "Object Sensor H",
    obj_sensor_i: "Object Sensor I",
    obj_sensor_j: "Object Sensor J",
    obj_sensor_k: "Object Sensor K",
    obj_sensor_l: "Object Sensor L",
    arrival_time: "Arrival time",
    ntp_local_time: "NTP local time",
    time_sync: "Time sync:",
    enable: "Enable",
    connect: "Connect",
    primary: "Primary",
    secondary: "Secondary",
    how_to_lux: "(How to configure Lux in ILV)",
    device: "Device:",
    device_part: "Device",
    processing_part: "Processing",
    address: "IP:",
    port: "Port:",
    import: "Import point cloud",
    record: "Record IDC file",
    vehicle_sample: "Output vehicle sample",
    only_support: "(Only data collected by plugin version 4~ supported)",
    without_object: "Objects output channel without post process",
    with_object: "Objects output channel with post process",
    without: "without post process",
    with: "with post process",
    signal_output: "Signals output:",
    origin: "Origin [m]:",
    yam_offset: "Yam offset[°]:",
    point_output: "Point cloud output channel:",
    merge2: "Merge 2 frame(For ECU connected with 8L)"
  }