var cn = {
  Enabled: "启用",
  source_Selection: "数据源选择",
  weather_type: "天气类型:",
  temperature: "温度:",
  humidity: "相对湿度:",
  pressure: "气压:",
  visibility: "能见度:",
  illumination: "光照:",
  wind_speed: "风速:",
  wind_direction: "风向:",
  disaster: "灾害:",
  road_name: "道路名称:",
  speed_limit: "限速:",
  road_type: "道路类型:",
  road_surface: "路面状况:",
  road_traffic: "道路交通状况:",
  lane_traffic: "车道交通状况:",
  spots: "场所:",
  typhoon: "(台风、龙卷风、闪电、冰雹等)",
  tunnel: "(隧道、事故、路口、桥等)",
  left: "左车道:",
  current: "本车道:",
  right: "右车道:",
  open: "畅通:",
  slow: "缓慢:",
  crowded: "拥挤:",
  reverse: "逆向:",
  devices: "设备接入",
  connect_rs: "连接RS485",
  web: "网络获取",
  data_holder: "数据保持:",
  sec: "[秒]",
  manual: "手动标记",
  baidu: "百度地图",
  seniverse: "心知天气",
  gaode: "高德地图",
  signal: "信号值",
  rs485: "RS485传感器",
  signals: "信号配置",
  not_config: "<未配置>",
  pm25: "PM 2.5:",
  pm10: "PM 10:",
  rainfall_source: "雨量:"
},
  en = {
    Enabled: "Enabled",
    source_Selection: "Source Selection",
    weather_type: "Weather type:",
    temperature: "Temperature:",
    humidity: "Humidity:",
    pressure: "Pressure:",
    visibility: "Visibility:",
    illumination: "Illumination:",
    wind_speed: "wind speed:",
    wind_direction: "Wind direction:",
    disaster: "Disaster:",
    road_name: "Road name:",
    speed_limit: "Speed limit:",
    road_type: "Road type:",
    road_surface: "Road surface:",
    road_traffic: "Road traffic:",
    lane_traffic: "Lane traffic:",
    spots: "Spots:",
    typhoon: "(Typhoon, tornado, lightning, hail, etc)",
    tunnel: "(Tunnel, accident, crossing, bridge, etc)",
    left: "Left:",
    current: "Current:",
    right: "Right:",
    open: "Open:",
    slow: "Slow:",
    crowded: "Crowded:",
    reverse: "Reverse:",
    devices: "Devices",
    connect_rs: "Connect RS485",
    web: "Web",
    data_holder: "Data Holder:",
    sec: "[sec]",
    manual: "Manual",
    baidu: "Baidu",
    seniverse: "Seniverse",
    gaode: "Gaode",
    signal: "Signal",
    rs485: "RS485",
    signals: "Signals",
    not_config: "<Not Configured>",
    pm25: "PM 2.5:",
    pm10: "PM 10:",
    rainfall_source: "Rainfall:"
  };