var cn = {
  add_module: "添加模块",
  import_module: "导入模块",
  export_module: "导出模块",
  remove_module: "移除模块",
  basic: "基础",
  enabled: "启用",
  freq: "频率:",
  name: "名称:",
  in: "输入信号:",
  none: "<无>",
  sample_in: "输入样本:",
  output_signal: "输出信号:",
  parameters: "参数列表",
  param_name: "参数名",
  param_val: "参数值",
  type_auto: "类型自动转换",
  cmd: "循环",
  cmd_start: "开始",
  cmd_end: "结束",
  save: "保存修改",
  abort: "放弃修改",
  import_path: "外部导入搜索路径",
  import_paths:"导入脚本搜索路径",
  cant_find: "在导入脚本搜索路径中无法找到bi_common.py",
  import_code: "导入代码",
  export_code: "导出代码",
  input_signal: "输入信号",
  input_add_signal: "添加",
  input_remove_signal: "移除",
  input_sample: "输入样本:",
  input_remove_sample: "移除",
  protocal: "协议名:",
  channel: "通道:",
  reload_sample: "更新",
  add_sample: "添加",
  output_siganl: "输出信号:",
  output_add_sample: "添加",
  output_remove_sample: "移除",
  output_sample: "输出样本:",
  output_channel: "输出通道别名",
  output_title: "输出样本标题(逗号分隔)",
  protocal_name: "协议名:",
  output_reload_sample: "更新",
  output_scene: "输出场景:",
  scene_id: "场景ID",
  scene_title: "属性标题(逗号分隔)",
  output_report: "输出报告:",
  add_report_id: "待添加报告的ID:",
  add_single_val: "添加单值报告",
  add_histogram: "添加柱状折线图报告",
  add_scatter_diagram: "添加散点图报告",
  add_matrix_diagram: "添加矩阵热力图报告",
  add_table_diagram: "添加表格热力图报告",
  sure: "确认",
  title: "标题:",
  SingleValue: "单值报告",
  MatrixTable: "矩阵热力图报告",
  x_title: "X轴标题:",
  y_title: "Y轴标题:",
  mode: "模式:",
  xiayan: "下沿",
  jiange: "间隔",
  geshu: "格数",
  matrix_fanwei: "数值显示范围:",
  LabelTable: "表格热力图报告",
  x_xiayan: "X轴范围下沿:",
  x_shangyan: "X轴范围上沿:",
  x_geshu: "X格数:",
  y_xiayan: "Y轴范围下沿:",
  y_shangyan: "Y轴范围上沿:",
  y_geshu: "Y格数:",
  title_split: "文字标签(逗号分隔):",
  hist_title: "柱状图标题:",
  histogram_title: "折线图标题:",
  scatter_report: "散点图报告",
  hist_report: "柱状折线图报告",
  default_val: "默认值:",
  nearest: "最近",
  chazhi: "插值",
  in_param_name: "参数名:",
  source_signal: "来源:",
  hist_def_val: "柱状图默认值:",
  line_def_val: "折线图默认值:",
  x_values: "X轴刻度:",
  numeric_mode: "数值模式",
  label_mode: "文字模式",
  val_direction: "数值方向:",
  remove_path: "移除",
  add_path: "添加",
  not_config:"<未配置>",
  normalmode:"一般模式",
  usetemplate:"使用模板",
  modifytemplate:"修改模板",
  template:"模板:",
  id:"模块ID:",
  id_legacy_mode:"按旧ID输出",
  templatemode:"模板模式",
  template_postfix:"ID后缀:",
  overwritefreq:"自定义频率:",
  overwriteparam:"自定义参数:",
  templateDefault:"默认",
  add_python_module:"添加Python模块",
  overwrite_freq:"频率:",
  overwritedef:"使用默认",
  overwriteParamter:"参数:",
  overwriteValue:"值:",
  overwritefreqtitle:"自定义频率",
  overwriteparamtitle:"自定义参数",
  parameter:"参数:",
  add_mode:"添加方式:",
  hz:"[赫兹]",
  signal:"信号:"
},
  en = {
    add_module: "Add module",
    import_module: "Import module",
    export_module: "Export module",
    remove_module: "Remove module",
    basic: "Basic",
    enabled: "Enabled",
    freq: "Freq:",
    name: "Name:",
    in: "Input signals:",
    input_signal: "Input signals",
    none: "<None>",
    sample_in: "Input samples:",
    output_signal: "Output signals:",
    output_sample: "Output samples:",
    output_scene: "Output scenes:",
    output_report: "Output reports:",
    parameters: "Parameters",
    param_name: "Name",
    param_val: "Value",
    type_auto: "Type auto-conversion",
    cmd: "Loop",
    cmd_start: "Start",
    cmd_end: "End",
    save: "Save",
    abort: "Abort",
    import_paths:"Import paths",
    import_path: "Import paths",
    cant_find: "Can't find bi_common.py in import paths",
    import_code: "Import code",
    export_code: "Export code",
    input_add_signal: "Add",
    input_remove_signal: "Remove",
    input_sample: "Input samples",
    input_remove_sample: "Remove",
    protocal: "Protocol:",
    channel: "Channel:",
    reload_sample: "Update",
    add_sample: "Add",
    output_siganl: "Output signals",
    output_add_sample: "Add",
    output_remove_sample: "Remove",
    output_channel: "Output Channel Name",
    output_title: "Output Sample Title(comma splitted)",
    protocal_name: "Protocol:",
    output_reload_sample: "Update",
    scene_id: "Scene ID",
    scene_title: "Property Title(comma splitted)",
    add_report_id: "Report ID to add:",
    add_histogram: "Add hist-line report",
    add_scatter_diagram: "Add scatter report",
    add_matrix_diagram: "Add matrix table report",
    add_table_diagram: "Add label table report",
    sure: "Confirm",
    add_single_val: "Add value report",
    title: "Title:",
    SingleValue: "Value report",
    MatrixTable: "Matrix table report",
    x_title: "X title:",
    y_title: "Y title:",
    mode: "Mode:",
    xiayan: "Base",
    jiange: "Step",
    geshu: "Count",
    matrix_fanwei: "Value range:",
    LabelTable: "Label table report",
    x_xiayan: "Lower-bound",
    x_shangyan: "Upper-bound",
    x_geshu: "Count",
    y_xiayan: "Lower-bound",
    y_shangyan: "Upper-bound",
    y_geshu: "Count",
    title_split: "Labels(comma splitted):",
    hist_title: "Hist title:",
    histogram_title: "Line title:",
    scatter_report: "Scatter report",
    hist_report: "Hist-line report",
    default_val: "Default value:",
    nearest: "Nearest",
    chazhi: "Interpolate",
    in_param_name: "Name:",
    source_signal: "Source:",
    hist_def_val: "Default hist value:",
    line_def_val: "Default line value:",
    x_values: "X values:",
    numeric_mode: "Numeric mode",
    label_mode: "Label mode",
    val_direction: "Value direction:",
    remove_path: "Remove",
    add_path: "Add",
    not_config:"<Not Configured>",
    normalmode:"Normal mode",
    usetemplate:"Use template",
    modifytemplate:"Modify template",
    template:"Template:",
    id:"Module ID:",
    templatemode:"Template mode",
    id_legacy_mode:"Output with legacy ID",
    template_postfix:"ID postfix:",
    overwritefreq:"Overwrite frequency:",
    overwriteparam:"Overwrite parameters:",
    templateDefault:"Default",
    add_python_module:"Add Python Module",
    overwrite_freq:"Frequency:",
    overwritedef:"Use default",
    overwriteParamter:"Parameter:",
    overwriteValue:"Value:",
    overwritefreqtitle:"Overwrite Frequency",
    overwriteparamtitle:"Overwrite Parameters",
    parameter:"Parameter:",
    add_mode:"Add mode:",
    hz:"[HZ]",
    signal:"Signal:"
  };