var cn = {
  enable: "Enable",
  serial_number: "Serial Number: ",
  record: "Record ",
  show_image: "Show Image",
  show_log: "Show Log",
  show_camera: "Show Camera",
  fram_rate: "Frame Rate:",
  accumulation_time_ang_fps: "Accumulation Time and FPS",
  event_rate_controller: "Event Rate Controller (Hardware)",
  accumulation_time: "Accumulation Time [ms]:",
  palette: "Palette:",
  enable_noise_filter: "Enable Noise Filter",
  enable_erc: "Enable ERC",
  event_per_second: "Events Per Second:",
  noise_filter: "Noise Filter (Hardware)",
  mode: "Mode:",
  noise_thresh: "Noise Thresh [us]:",
  activity_noise_filter: "Activity Noise Filter (Software)",
  enabled_activity_noise_filter: "Enable Activity Noise Filter",
  activity_thresh: "Activity Thresh [us]:",
  anti_flicker_filter: "Anti-flicker Filter (Software)",
  enable_anti_flicker_filter: "Enable Anti-flicker Filter",
  output_all_burst_events: "Output All Burst Events",
  difference_thresh: "Difference Thresh [us]:",
  anti_flicker_length: "Anti-flicker Length ",
  output_frequency_range: "Output Frequency Range [Hz]: ",
  file_path: "File Path:",
  not_select: "<Not Select>",
  save_path: "Save Path: ",
  anti_flicker: "Anti-flicker (Hardware)",
  enable_antiflicker: "Enable Antiflicker",
  band_frequency_range: "Band Frequency Range [Hz]:",
  polarity_filter_algorithm: "Polarity Filter Algorithm (Software)",
  enable_polarity_filter: "Enable Polarity Filter",
  polarity: "Polarity :",
  spatio_temporal_contrast_filter: "Spatio Temporal Contrast Filter (Software)",
  enable_stc: "Enable STC",
  cut_trail:"Cut Trail",
  trail_filter:"Trail Filter (Software)",
  enable_trail_filter:"Enable Trail Filter",
  trail_thresh:"Trail Thresh [us]:",
  band_stop: "Band Stop",
  stc_thresh: "STC Thresh [us]:",
  million:"[million]"
},
  en = {
    serial_number: "Serial Number: ",
    record: "Record ",
    show_image: "Show Image",
    show_log: "Show Log",
    show_camera: "Show Camera",
    accumulation_time_ang_fps: "Accumulation Time and FPS",
    fram_rate: "Frame Rate:",
    accumulation_time: "Accumulation Time [ms]:",
    palette: "Palette:",
    event_rate_controller: "Event Rate Controller (Hardware)",
    enable_noise_filter: "Enable Noise Filter",
    enable_erc: "Enable ERC",
    event_per_second: "Events per Sceond:",
    noise_filter: "Noise Filter (Hardware)",
    mode: "Mode:",
    noise_thresh: "Noise Thresh [us]:",
    activity_noise_filter: "Activity Noise Filter (Software)",
    enabled_activity_noise_filter: "Enable Activity Noise Filter",
    activity_thresh: "Activity Thresh [us]:",
    anti_flicker_filter: "Anti-flicker Filter (Software)",
    enable_anti_flicker_filter: "Enable Anti-flicker Filter",
    output_all_burst_events: "Output All Burst Events",
    difference_thresh: "Difference Thresh [us]:",
    anti_flicker_length: "Anti-flicker Length ",
    output_frequency_range: "Output Frequency Range [Hz]: ",
    file_path: "File Path:",
    not_select: "<Not Select>",
    save_path: "Save Path: ",
    anti_flicker: "Anti-flicker (Hardware)",
    enable_antiflicker: "Enable Antiflicker",
    band_stop: "Band Stop",
    band_frequency_range: "Band Frequency Range [Hz]:",
    polarity_filter_algorithm: "Polarity Filter Algorithm (Software)",
    enable_polarity_filter: "Enable Polarity Filter",
    polarity: "Polarity :",
    spatio_temporal_contrast_filter: "Spatio Temporal Contrast Filter (Software)",
    enable_stc: "Enable STC",
    stc_thresh: "STC Thresh [us]:",
    cut_trail:"Cut Trail",
    trail_filter:"Trail Filter (Software)",
    enable_trail_filter:"Enable Trail Filter",
    trail_thresh:"Trail Thresh [us]:",
    million:"[million]"
  };