var cn = {
    swap: "切换",
    enabled: "启动",
    not_config: "<未配置>",
    signal: "信号:",
    select_node: "选中节点",
    not_select: "<未选择>",
    id: "ID:",
    type: "类型:",
    edit: "编辑",
    remove: "移除",
    signal_i_o: "信号I/O",
    input_signal: "输入",
    output_signal: "输出",
    constant: "常数",
    unary_operators: "一元运算符",
    condition: "条件",
    add: "加",
    add2: "加:",
    multiply: "乘",
    multiply2: "乘:",
    abs: "绝对值",
    power: "乘幂",
    power2: "乘幂:",
    holder: "保持",
    ceil: "上取整",
    floor: "下取整",
    round: "四舍五入",
    avg: "平均值",
    integral: "积分",
    map: "映射",
    st_order: "一阶低通虑波",
    mod: "模",
    mod2: "模:",
    binary_operators: "二元运算符",
    and: "与",
    or: "或",
    subtract: "减",
    divide: "除",
    weighted: "加权平均",
    resettable: "可重置积分",
    ternary: "三元运算符",
    if_else: "条件分支",
    in_range: "是否范围内",
    clamp: "范围限制",
    multiple_oper: "多元运算符",
    min: "最小",
    max: "最大",
    options: "选项",
    sampling_rate: "采样率 [Hz]:",
    signal_input: "输入",
    interpolation: "插值方式:",
    linear: "线性",
    nearest: "最近",
    signal_output: "输出",
    output_signal_name: "输出信号名:",
    value: "数值:",
    condition_with_number: "条件",
    reset_cond: "重置条件:",
    add_number: "加(输入负数即为减)",
    multiply_number: "乘",
    default: "默认值:",
    while_input: "当输入 ≤0",
    signal_holder: "保持",
    hold_duration: "保持时间:",
    s: "[秒]",
    number_map: "数值映射",
    passthrough: "原值输出",
    constant_: "输出常数=",
    time_coefficient: "时间常数:",
    mod_number: "模数(必须>0)",
    subtract_signal: "相减",
    divide_signal: "除",
    while_zero_devision: "当零除时",
    condition_with_signal: "条件",
    weighted_average: "加权平均",
    weight: "权重 : ",
    reset: "重置 : ",
    while_zero: "为0时",
    if_the_follow: "若以下信号值为0:",
    then_output: "则输出:",
    else_output: "否则输出:",
    input_value: "输入值:",
    lower_bound: "下界:",
    upper_bound: "上界:",
    clamp_signal: "范围限制",
    input: "输入",
    output: "输出",
  },
  en = {
    input: "Input",
    output: "Output",
    swap: "SWAP",
    multiply_number: "Multiply number",
    enabled: "Enabled",
    not_config: "<Not Configured>",
    select_node: "Selected node",
    not_select: "<Not Selected>",
    id: "ID:",
    type: "Type:",
    edit: "Edit",
    remove: "Remove",
    signal_i_o: "Signal I/O",
    input_signal: "Input signal",
    output_signal: "Output signal",
    constant: "Constant",
    unary_operators: "Unary operators",
    condition: "Condition",
    add: "Add",
    add2: "Add:",
    multiply: "Multiply",
    multiply2: "Multiply:",
    abs: "Absolute",
    power: "Power",
    power2: "Power:",
    holder: "Holder",
    ceil: "Ceiling",
    floor: "Floor",
    round: "Round",
    avg: "Average",
    integral: "Integral",
    map: "Map",
    st_order: "1st-order LPF",
    mod: "Mod",
    mod2: "Mod:",
    binary_operators: "Binary operators",
    and: "And",
    or: "Or",
    subtract: "Subtract",
    divide: "Divide",
    weighted: "Weighted average",
    resettable: "Resettable integeral",
    ternary: "Ternary operators",
    if_else: "If-else",
    in_range: "In-range",
    clamp: "Clamp",
    multiple_oper: "Multiple operators",
    min: "Minimum",
    max: "Maximum",
    options: "Options",
    sampling_rate: "Sampling rate [Hz]:",
    signal_input: "Signal input",
    signal: "Signal:",
    interpolation: "Interpolation:",
    linear: "Linear",
    nearest: "Nearest",
    signal_output: "Signal output",
    output_signal_name: "Output signal name:",
    value: "Value:",
    condition_with_number: "Condition with number",
    reset_cond: "Reset condition:",
    add_number: "Add number",
    default: "Default:",
    while_input: "while input ≤0",
    signal_holder: "Signal holder",
    hold_duration: "Hold duration:",
    s: "[s]",
    number_map: "Number Mapping",
    passthrough: "Passthrough",
    constant_: "Constant=",
    time_coefficient: "Time coefficient:",
    mod_number: "Mod number",
    subtract_signal: "Subtract signal",
    divide_signal: "Divide signal",
    while_zero_devision: "while zero-devision",
    condition_with_signal: "Condition with signal",
    weighted_average: "Weighted average",
    weight: "Weight : ",
    reset: "Reset : ",
    while_zero: "while zero",
    if_the_follow: "If the following signal is zero:",
    then_output: "then output:",
    else_output: "else output:",
    input_value: "Input value:",
    lower_bound: "Lower bound:",
    upper_bound: "Upper bound:",
    clamp_signal: "Clamp signal",

  };

var cn2 = {
  "Input signal": "输入",
  "Output signal": "输出",
  "Input constant": "常数",
  "Condition with number": "条件",
  "Add / Subtract number": "加",
  "Multiply number": "乘",
  "Absolute": "绝对值",
  "power": "乘幂",
  "pow": "乘幂:",
  "Signal holder": "保持",
  "Ceiling": "上取整",
  "Floor": "下取整",
  "Round": "四舍五入",
  "Average": "平均",
  "Integral": "积分",
  "Number mapping": "映射",
  "1st low pass filter": "一阶低通滤波",
  "Mod number": "模",
  "Logical and": "与",
  "Logical or": "或",
  "Add signal": "相加",
  "Subtract signal": "相减",
  "Multiply signal": "相乘",
  "Divide": "除",
  "Condition with signal": "条件",
  "Weighted average": "加权平均",
  "Resettable integeral": "可重置积分",
  "If-else condition": "条件分支",
  "In-range condition": "是否范围内",
  "clamp": "范围限制",
  "Minimum": "最小",
  "Maximum": "最大",
}