var cn = {
  enable: "启用",
  only_xyzi: '仅 XYZI',
  local_path: '本地路径',
  empty: '<空>',
  binary: '二进制',
  ascii: 'ASCII',
  binary_compressed: '二进制压缩',
  absolute_time_file:'绝对时间文件名',
  absolute_time_points:'绝对时间点云',
  channelFiltering:'通道过滤',
  timeOffset:"时间偏移[毫秒]:",
  output:"输出",
  process:"处理模式",
  offline_processing_mode:"离线处理模式",
  offline_postprocessing_mode:"离线后处理模式(文件i/o)",
  other_path:"其他路径:",
  time_sync_type:"时间同步类型:"
},
en = {
  enable: "Enable",
  only_xyzi: 'Only XYZI',
  local_path: 'Local path',
  empty: '<Empty>',
  binary: 'Binary',
  ascii: 'ASCII',
  binary_compressed: 'Binary compressed',
  absolute_time_file:'Absolute time file',
  absolute_time_points:'Absolute time points',
  channelFiltering:'Channel filtering',
  timeOffset:"Time offset [ms]:",
  output:"Output",
  process:"Process Mode",
  offline_processing_mode:"Offline processing mode",
  offline_postprocessing_mode:"Offline post-processing mode(file i/o)",
  other_path:"Other path:",
  time_sync_type:"Time sync type:"
};