var cn = {
  enabled: "启用",
  not_config: "<未配置>",
  add_signal: "添加信号",
  add_msgs: "批量添加报文信号",
  add_signals: "批量添加多个信号",
  add_schedule: "添加计划事件",
  add_signal_event: "添加信号事件",
  add_manual: "添加手动触发器事件",
  importAsc: "导入配置",
  exportAsc: "导出配置",
  mail_set: "邮件发送配置",
  trigger_cond: "触发条件:",
  snap: "快照",
  data_table: "数据表:",
  no_data: "无数据",
  send_mail: "发送邮件",
  video_view: "视频图:",
  bird_view: "俯瞰图:",
  session_record: "Session采集",
  range: "采集范围[s]: - ",
  meg_tran: "报文发送",
  not_tran: "不发送",
  location_source: "位置源:",
  schedule_event: "计划事件",
  name: "名称:",
  signal_event: "信号事件",
  signal: "信号:",
  manual_tr_event: "手动触发器事件",
  channel: "通道:",
  mail_send_cfg: "邮件发送配置",
  basic_info: "基本信息",
  from: "来自:",
  to: "发送至:",
  title_set: "标题设定",
  title: "标题:",
  add_event_type: "含事件类型",
  add_data_and_time: "含日期和时间",
  smtp_set: "SMTP设定",
  server: "服务器:",
  us_ssl: "使用SSL",
  user: "用户:",
  password: "密码:",
  remember: "记住密码(加密)",
  signal_of_event: "事件信号表",
  tran_msg_for_event: "事件触发报文发送",
  add_msg: "添加报文",
  disabled: "(禁用)",
  chan_a: "通道A",
  chan_b: "通道B",
  chan_c: "通道C",
  chan_d: "通道D",
  chan_e: "通道E",
  chan_f: "通道F",
  chan_g: "通道G",
  chan_h: "通道H",
  chan_i: "通道I",
  chan_j: "通道J",
  chan_k: "通道K",
  chan_l: "通道L",
  chan_m: "通道M",
  chan_n: "通道N",
  chan_o: "通道O",
  chan_p: "通道P",
  chan_q: "通道Q",
  chan_r: "通道R",
  chan_s: "通道S",
  chan_t: "通道T",
  chan_u: "通道U",
  chan_v: "通道V",
  chan_w: "通道W",
  chan_x: "通道X",
  obj_chan_a: "目标物传感器A",
  obj_chan_b: "目标物传感器B",
  obj_chan_c: "目标物传感器C",
  obj_chan_d: "目标物传感器D",
  obj_chan_e: "目标物传感器E",
  obj_chan_f: "目标物传感器F",
  obj_chan_g: "目标物传感器G",
  obj_chan_h: "目标物传感器H",
  obj_chan_i: "目标物传感器I",
  obj_chan_j: "目标物传感器J",
  obj_chan_k: "目标物传感器K",
  obj_chan_l: "目标物传感器L",
  lane_chan_a: "车道线传感器A",
  lane_chan_b: "车道线传感器B",
  lane_chan_c: "车道线传感器C",
  lane_chan_d: "车道线传感器D",
  any_chan: "任意通道",
  gnss_imu_chan_a: "组合惯导通道A",
  gnss_imu_chan_b: "组合惯导通道B",
  gnss_imu_chan_c: "组合惯导通道C",
  gnss_imu_chan_d: "组合惯导通道D",
  gnss_imu_chan_e: "组合惯导通道E",
  gnss_imu_chan_f: "组合惯导通道F",
  session_alert: "连续采集模式不支持事件session生成，是否切换至事件触发采集模式？",
  confirmAlert:"确认",
},
  en = {
    disabled: "(Disabled)",
    chan_a: "Channel A",
    chan_b: "Channel B",
    chan_c: "Channel C",
    chan_d: "Channel D",
    chan_e: "Channel E",
    chan_f: "Channel F",
    chan_g: "Channel G",
    chan_h: "Channel H",
    chan_i: "Channel I",
    chan_j: "Channel J",
    chan_k: "Channel K",
    chan_l: "Channel L",
    chan_m: "Channel M",
    chan_n: "Channel N",
    chan_o: "Channel O",
    chan_p: "Channel P",
    chan_q: "Channel Q",
    chan_r: "Channel R",
    chan_s: "Channel S",
    chan_t: "Channel T",
    chan_u: "Channel U",
    chan_v: "Channel V",
    chan_w: "Channel W",
    chan_x: "Channel X",
    obj_chan_a: "Object Channel A",
    obj_chan_b: "Object Channel B",
    obj_chan_c: "Object Channel C",
    obj_chan_d: "Object Channel D",
    obj_chan_e: "Object Channel E",
    obj_chan_f: "Object Channel F",
    obj_chan_g: "Object Channel G",
    obj_chan_h: "Object Channel H",
    obj_chan_i: "Object Channel I",
    obj_chan_j: "Object Channel J",
    obj_chan_k: "Object Channel K",
    obj_chan_l: "Object Channel L",
    lane_chan_a: "Lane Channel A",
    lane_chan_b: "Lane Channel B",
    lane_chan_c: "Lane Channel C",
    lane_chan_d: "Lane Channel D",
    any_chan: "Any channels",
    gnss_imu_chan_a: "GNSS-IMU channel A",
    gnss_imu_chan_b: "GNSS-IMU channel B",
    gnss_imu_chan_c: "GNSS-IMU channel C",
    gnss_imu_chan_d: "GNSS-IMU channel D",
    gnss_imu_chan_e: "GNSS-IMU channel E",
    gnss_imu_chan_f: "GNSS-IMU channel F",
    add_signal: "Add signal",
    add_msgs: "Add message's signals",
    add_signals: "Add several signals",
    enabled: "Enabled",
    not_config: "<Not Configured>",
    add_schedule: "Add schedule event",
    add_signal_event: "Add signal event",
    add_manual: "Add manual trigger event",
    importAsc: "Import config",
    exportAsc: "Export config",
    mail_set: "Mail settings",
    trigger_cond: "Trigger condition:",
    snap: "Snapshot",
    data_table: "Data table:",
    no_data: "No data",
    send_mail: "Send mail",
    video_view: "Video view:",
    bird_view: "Bird view:",
    session_record: "Session Recording",
    range: "Range[s]: - ",
    meg_tran: "Message transmit",
    not_tran: "Not transmit",
    location_source: "Location source:",
    schedule_event: "Scheduled event",
    name: "Name:",
    signal_event: "Signal event",
    signal: "Signal:",
    manual_tr_event: "Manual trigger event",
    channel: "Channel:",
    mail_send_cfg: "Mail sending configuration",
    basic_info: "Basic information",
    from: "From:",
    to: "To:",
    title_set: "Title settings",
    title: "Title:",
    add_event_type: "Add event type",
    add_data_and_time: "Add date and time",
    smtp_set: "SMTP settings",
    server: "Server:",
    us_ssl: "Using SSL",
    user: "User:",
    password: "Password:",
    remember: "Remember password (encrypted)",
    signal_of_event: "Signals of event",
    tran_msg_for_event: "Transmit messages for event",
    add_msg: "Add message",
    session_alert: " Event session recording is not supported by continuous recording mode. Do you want to switch to event-triggered recording mode?",
    confirmAlert:"Confirm",
  };