var cn = {
    id_sig: "ID信号:",
    enabled: "启用",
    final_msg: "帧尾报文: ",
    not_config: "<未配置>",
    traffic_info: "交通信息",
    out_channel: "输出通道:",
    origin_x: "原点[m]: ",
    yaw_offset: "横摆角偏置[deg]: ",
    elements: "交通元素",
    speed_limit: "限速",
    stop_sign: "停止标志",
    traffic_light: "红绿灯",
    stop_line: "停止线",
    speed_bump: "减速带",
    arrow_mark: "箭头标志",
    pro_zone: "禁停区",
    park_slot: "停车位",
    zebra_cro: "斑马线",
    valid_sig: "有效信号:",
    valid_value: "有效值:",
    limit_speed_sig: "限速信号:",
    sign_pos_x_sig: "标志X轴位置信号:",
    sign_pos_y_sig: "标志Y轴位置信号:",
    sign_pos_z_sig: "标志Z轴位置信号:",
    pos_x_sig: "X轴位置信号:",
    pos_y_sig: "Y轴位置信号:",
    pos_z_sig: "Z轴位置信号:",
    light_state_sig: "信号灯状态信号:",
    stop_v: "红灯信号值:",
    allow_v: "绿灯信号值:",
    continue_v: "黄灯信号值:",
    arrow_comb: "箭头组合",
    str_v: "直行信号值:",
    turn_v: "调头信号值:",
    left_v: "左转信号值:",
    right_v: "右转信号值:",
    arrow_type_sig: "箭头类型信号:",
    arrow_di_comb: "箭头方向组合",
    center_pos_x_sig: "中心位置X轴位置信号:",
    center_pos_y_sig: "中心位置Y轴位置信号:",
    w_sig: "宽度信号:",
    l_sig: "长度信号:",
    near_vound_sig: "近边距离信号:",
    far_bound_sig: "远边距离信号:",
    remove: "移除",
    distance_sig: "距离信号:",
    head_sig: "朝向信号:",
    out_sample_version: "输出样本版本:",
    scale_small: "比例:小范围",
    scale_large: "比例:大范围",
    traffic_sen_a: "交通信息通道A",
    traffic_sen_b: "交通信息通道B",
    traffic_sen_c: "交通信息通道C",
    traffic_sen_d: "交通信息通道D",
    cauion_v: "黄闪信号值:",
    stop_flash_v: "红闪信号值:",
    allow_flash_v: "绿闪信号值:",
  },
  en = {
    pos_z_sig: "Position-Z sig:",
    id_sig: "ID sig:",
    traffic_sen_a: "Traffic Sensor A",
    traffic_sen_b: "Traffic Sensor B",
    traffic_sen_c: "Traffic Sensor C",
    traffic_sen_d: "Traffic Sensor D",
    enabled: "Enabled",
    final_msg: "Final msg: ",
    not_config: "<Not Configured>",
    traffic_info: "Traffic Info",
    out_channel: "Output Channel:",
    origin_x: "Origin [m]: ",
    yaw_offset: "Yaw offset [deg]: ",
    elements: "Elements",
    speed_limit: "Speed limit",
    stop_sign: "Stop sign",
    traffic_light: "Traffic light",
    stop_line: "Stop line",
    speed_bump: "Speed bump",
    arrow_mark: "Arrow mark",
    pro_zone: "Prohibition zone",
    park_slot: "Parking slot",
    zebra_cro: "Zebra crossion",
    valid_sig: "Valid sig:",
    valid_value: "Valid value:",
    limit_speed_sig: "Limited speed sig:",
    sign_pos_x_sig: "Sign position-X sig:",
    sign_pos_y_sig: "Sign position-Y sig:",
    sign_pos_z_sig: "Sign position-Z sig:",
    pos_x_sig: "Position-X sig:",
    pos_y_sig: "Position-Y sig:",
    light_state_sig: "Light state sig:",
    stop_v: "Stop values:",
    allow_v: "Allow values:",
    continue_v: "Continue values:",
    cauion_v: "Caution values:",
    arrow_comb: "Arrow combination",
    str_v: "Straight values:",
    turn_v: "U-turn values:",
    left_v: "Left values:",
    right_v: "Right values:",
    arrow_type_sig: "Arrow type sig:",
    arrow_di_comb: "Arrow direction combination",
    center_pos_x_sig: "Center position-X sig:",
    center_pos_y_sig: "Center position-Y sig:",
    w_sig: "Width sig:",
    l_sig: "Length sig:",
    head_sig: "Heading sig:",
    near_vound_sig: "Near-bound distance sig:",
    far_bound_sig: "Far-bound distance sig:",
    remove: "Remove",
    distance_sig: "Distance sig:",
    out_sample_version: "Output sample version:",
    scale_small: "Scale: Small",
    scale_large: "Scale: Large",
    stop_flash_v: "Stop flash values:",
    allow_flash_v: "Allow flash values:",
  };