var cn = {
  ProjectName:"项目名称",
  TestFunction:"测试功能",
  SubTestFunction:"子功能",
  Tester:"测试人员",
  Version:"软件版本",
  DateTime:"测试时间",
  VehicleWidth:"车长(m)",
  VehicleLength:"车宽(m)",
  FrontParkingSpace:"前部空间(m)",
  sure:"确定",
},
en = {
  ProjectName:"Project name",
  TestFunction:"Test function",
  SubTestFunction:"Sub function",
  Tester:"Tester name",
  Version:"Version",
  DateTime:"Test date",
  VehicleWidth:"Vehicle length(m)",
  VehicleLength:"Vehicle width(m)",
  FrontParkingSpace:"Front parking space(m)",
  sure:"OK",
};