var cn = {
  kb_data: 'KB数据',
  data_sourse: '数据源',
  hdmap_files: '高精地图文件',
  map_sourse: '地图文件',
  external_hdMap: '外部高精地图',
  ibeo_evs: 'IBEO EVS的后处理(map-evs.xodr)',
  lane_sensor_sample: '车道线传感器样本的后处理(map-lss.xodr)',
  gnss_imu_sample: 'GNSS-IMU样本的后处理(map-gis.xodr)',
  external_geo_json: '外部 Geo Json',
  external_shape_file: '外部 Shape File',
  not_config: '<未配置>',
  processing: '数据处理',
  gnss_imu_input: 'GNSS-IMU输入通道:',
  disabled: '(未启用)',
  visible_area_region: '可视区域:',
  fine_interval: '间隔[m]:'
},
  en = {
    kb_data: 'KB Data',
    data_sourse: 'Data Sourse',
    hdmap_files: 'HDMap Files',
    map_sourse: 'Map Source',
    external_hdMap: 'External HDMap',
    ibeo_evs: 'Post processed by IBEO EVS(map-evs.xodr)',
    lane_sensor_sample: 'Post processed by lane sensor sample(map-lss.xodr)',
    gnss_imu_sample: 'Post processed by gnss imu sample(map-gis.xodr)',
    external_geo_json: 'External Geo Json',
    external_shape_file: 'External Shape File',
    not_config: '<Not Configured>',
    processing: 'Processing',
    gnss_imu_input: 'GNSS-IMU input channel:',
    disabled: '(Disabled)',
    visible_area_region: 'Visible Area Region:',
    fine_interval: 'Fine interval[m]:'
  };