var cn = {
        output_sample_version: "输出样本版本",
        lane_sensor: "车道线传感器",
        enabled: "启用",
        final_msg: '帧尾报文:',
        not_cfg: " <未配置>",
        out_channel: "输出通道:",
        coor_offset: "坐标偏置",
        origin: "原点[m]:",
        yaw_offset: "横摆角偏置[deg]:",
        line_type_v: "类型信号值",
        other_type: "其他类型",
        solid: "实线:",
        dashed: "虚线:",
        line_color_v: "颜色信号值",
        white: "白:",
        yellow: "黄:",
        model_type: "方程类型",
        heading: "朝向",
        curvature: "曲率",
        curvature_diff: "曲率微分",
        detect_range: "探测范围",
        rear: "后向[m]:",
        front: "前向[m]:",
        scale_small: "比例: 小范围",
        scale_large: "比例: 大范围",
        lane_line: "车道线",
        add_lane_line: "添加车道线",
        valid_signal: "有效位信号:",
        id_signal: "ID信号:",
        line_type: "类型:",
        line_color: "线色:",
        confidence: "置信度:",
        line_width: "线宽[米]:",
        rear_end: "后端[米]:",
        front_end: "前端[米]:",
        valid_v: "有效值:",
        remove: "移除",
        distance_to_line: "线间距离[米]:",
        other_color_types: "其他颜色",
        other_line_types: "其他类型",
        double_solid: "双实线:",
        double_dash: "双虚线:",
        solid_dash: "左实右虚:",
        dash_solid: "左虚右实:",
        road_curb: "路沿:",
        guardrail: "护栏:",
        barrier: "障碍物:",
        red: "红:",
        blue: "蓝:",
        orange: "橙:",
        green: "绿:",
        lane_sen_a: "车道线传感器A",
        lane_sen_b: "车道线传感器B",
        lane_sen_c: "车道线传感器C",
        lane_sen_d: "车道线传感器D",
        lane_sen_e: "车道线传感器E",
        lane_sen_f: "车道线传感器F",
        lane_sen_g: "车道线传感器G",
        lane_sen_h: "车道线传感器H",
        clothoid: "回旋曲线",
        mathematic: "多项式",
        import:"导入",
        export:"导出"
    },
    en = {
        clothoid: "Clothoid",
        mathematic: "Mathematic",
        lane_sen_a: "Lane Sensor A",
        lane_sen_b: "Lane Sensor B",
        lane_sen_c: "Lane Sensor C",
        lane_sen_d: "Lane Sensor D",
        lane_sen_e: "Lane Sensor E",
        lane_sen_f: "Lane Sensor F",
        lane_sen_g: "Lane Sensor G",
        lane_sen_h: "Lane Sensor H",
        other_color_types: "Other color types",
        other_line_types: "Other line types",
        output_sample_version: "Output sample version",
        lane_sensor: "Lane Sensor",
        enabled: "Enabled",
        final_msg: 'Final msg:',
        not_cfg: "<Not configured>",
        out_channel: "Output Channel:",
        coor_offset: "Coordination offset",
        origin: "Origin [m]:",
        yaw_offset: "Yaw offset [deg]:",
        line_type_v: "Line type signal values",
        other_type: "Other types",
        solid: "Solid:",
        dashed: "Dashed:",
        line_color_v: "Line color signal values",
        white: "White:",
        yellow: "Yellow:",
        model_type: "Model type",
        heading: "Heading",
        curvature: "Curvature",
        curvature_diff: "Curvature diff.",
        detect_range: "Detect range",
        rear: "Rear [m]:",
        front: "Front [m]:",
        scale_small: "Scale: Small",
        scale_large: "Scale: Large",
        lane_line: "Lane lines",
        add_lane_line: "Add lane line",
        valid_signal: "Valid signal:",
        id_signal: "ID signal:",
        line_type: "Line type:",
        line_color: "Line color:",
        confidence: "Confidence:",
        line_width: "Line width[m]:",
        rear_end: "Rear end [m]:",
        front_end: "Front end [m]:",
        valid_v: "Valid value:",
        remove: "Remove",
        distance_to_line: "Distance to Line [m]:",
        double_solid: "Double solid:",
        double_dash: "Double dashed:",
        solid_dash: "Solid-dashed:",
        dash_solid: "Dashed-solid:",
        road_curb: "Road curb:",
        guardrail: "Guardrail:",
        barrier: "Barrier:",
        red: "Red:",
        blue: "Blue:",
        orange: "Orange:",
        green: "Green:",
        import:"Import",
        export:"Export"
    };