let cn = {
  lidar1: "激光雷达1",
  lidar2: "激光雷达2",
  lidar3: "激光雷达3",
  lidar4: "激光雷达4",
  lidar5: "激光雷达5",
  lidar6: "激光雷达6",
  output: "输出",
  point_cloud_output_channel: "点云输出通道:",
  point_map_output_channel: "点映射输出通道:",
  input: "输入",
  bus_channel: "总线通道:",
  message_id: "消息 ID:",
  processing: "处理",
  device_type: "设备类型:",
  frame_split_angle: "帧分割角 [deg]:",
  origin: "原点 [m]:",
  yam_offset: "Yam偏移量[°]:",
  disabled: "(禁用)",
  channel_a: "通道 A",
  channel_b: "通道 B",
  channel_c: "通道 C",
  channel_d: "通道 D",
  channel_e: "通道 E",
  channel_f: "通道 F",
  posture: "角度 [°]:",
  pitch: "倾斜度",
  roll: "旋转",
  height: "高",
  frame_timestamp_ratio: "帧时间戳比率:",
  roll_lock: "防旋转",
  yaw_lock: "防偏航",
  yaw: "偏航",
  fine: "精细",
  utc_time_sync: "UTC时间同步",
  clip_point_cloud:"点云剪裁",
  clip_min_height:"最小高度:",
  monitor:"监控",
  lidar_packet_monitor:"雷达包监控",
  delta_offset_thresh:"到达时间差值阈值:",
  delta_angle_thresh:"Posix差值阈值:",
  delta_posix_thresh:"角度差值阈值:",
  sync_time_offset:"时间偏移同步[毫秒]:",
  time_sync_type:"时间同步类型:",
  clip_max_height:"最大高度:"
},
  en = {
    lidar1: "Lidar1",
    lidar2: "Lidar2",
    lidar3: "Lidar3",
    lidar4: "Lidar4",
    lidar5: "Lidar5",
    lidar6: "Lidar6",
    output: "Output",
    point_cloud_output_channel: "Point cloud output channel:",
    point_map_output_channel: "Point map output channel:",
    input: "Input",
    bus_channel: "Bus channel:",
    message_id: "Message ID:",
    processing: "Processing",
    device_type: "Device type:",
    frame_split_angle: "Frame split angle [deg]:",
    origin: "Origin [m]:",
    yam_offset: "Yam offset[°]:",
    disabled: "(Disabled)",
    channel_a: "Channel A",
    channel_b: "Channel B",
    channel_c: "Channel C",
    channel_d: "Channel D",
    channel_e: "Channel E",
    channel_f: "Channel F",
    posture: "Posture [°]:",
    pitch: "Pitch",
    roll: "Roll",
    height: "H",
    frame_timestamp_ratio: "Frame timestamp ratio:",
    roll_lock: "Roll lock",
    yaw_lock: "Yaw lock",
    yaw: "Yaw",
    fine: "Fine",
    utc_time_sync: "UTC Time Sync",
    clip_point_cloud:"Clip point cloud",
    clip_min_height:"Min height:",
    lidar_packet_monitor:"Lidar Packet Monitor",
    monitor:"Monitor",
    delta_offset_thresh:"Delta offset:",
    delta_angle_thresh:"Delta angle:",
    delta_posix_thresh:"Delta posix:",
    sync_time_offset:"Sync time offset[ms]:",
    time_sync_type:"Time sync type:",
    clip_max_height:"Max height:"
  }