var cn = {
  m1_lidar: "雷达",
  input: "输入",
  msgID: "报文ID:",
  ip: "IP:",
  processing: "处理",
  disabled: "(未启用)",
  outputChannel: "目标物数据输出通道:",
  origin: "起始点 [m]:",
  yaw: "偏航角度[度]:",
  mode: "模式:",
  port: "端口号:",
  connect: "连接",
  scale: "比例:小范围",
  objectSensorA: "目标物传感器A",
  objectSensorB: "目标物传感器B",
  objectSensorC: "目标物传感器C",
  objectSensorD: "目标物传感器D",
  objectSensorE: "目标物传感器E",
  objectSensorF: "目标物传感器F",
  objectSensorG: "目标物传感器G",
  objectSensorH: "目标物传感器H",
  objectSensorI: "目标物传感器I",
  objectSensorJ: "目标物传感器J",
  objectSensorK: "目标物传感器K",
  objectSensorL: "目标物传感器L",
},
  en = {
    m1_lidar: "Lidar",
    connect: " Connect",
    input: "Input",
    msgID: "Message ID:",
    ip: "IP:",
    processing: "Processing",
    disabled: "(Disabled)",
    outputChannel: "Output objects channel:",
    origin: "Origin [m]:",
    yaw: "Yaw offset [deg]:",
    mode: "Mode:",
    port: "Port:",
    scale: "Scale:small",
    objectSensorA: "Object sensor A",
    objectSensorB: "Object sensor B",
    objectSensorC: "Object sensor C",
    objectSensorD: "Object sensor D",
    objectSensorE: "Object sensor E",
    objectSensorF: "Object sensor F",
    objectSensorG: "Object sensor G",
    objectSensorH: "Object sensor H",
    objectSensorI: "Object sensor I",
    objectSensorJ: "Object sensor J",
    objectSensorK: "Object sensor K",
    objectSensorL: "Object sensor L",
  };