var cn = {
  connect: "连接",
  com_port: "COM端口号:",
  com_baud_rate: "COM端口波特率:",
  output_channel: "输出通道:",
  device_part: "设备",
  device_type: "设备类型:",
  processing_part: "处理",
  b48: "4800 波特",
  b96: "9600 波特",
  b192: "19200 波特",
  b384: "38400 波特",
  b576: "57600 波特",
  b1152: "115200 波特",
  b2304: "230400 波特",
  b4608: "460800 波特",
  disabled: "(禁用)",
  gnss_imu_a: "GNSS-IMU 传感器 A",
  gnss_imu_b: "GNSS-IMU 传感器 B",
  gnss_imu_c: "GNSS-IMU 传感器 C",
  gnss_imu_d: "GNSS-IMU 传感器 D",
  gnss_imu_e: "GNSS-IMU 传感器 E",
  gnss_imu_f: "GNSS-IMU 传感器 F",
  yaw_rate: '横摆率:',
  pitch_offset: "俯仰偏移:",
  roll_offset: "横滚偏移:",
  novatel_imu_type:"诺瓦泰IMU型:",
  time_type:"时间类型:",
  heading_offset:"航向偏移量:",
  pos:"位置(m):",
  connect_gps_comm:"连接GPS COM端口",
  send_command:"发送指令",
  com2_port:"COM2端口号:",
  connect_comm:"连接指令:"
},
  en = {
      b48: "4800 Baud",
      b96: "9600 Baud",
      b192: "19200 Baud",
      b384: "38400 Baud",
      b576: "57600 Baud",
      b1152: "115200 Baud",
      b2304: "230400 Baud",
      b4608: "460800 Baud",
      disabled: "(Disabled)",
      gnss_imu_a: "GNSS-IMU Sensor A",
      gnss_imu_b: "GNSS-IMU Sensor B",
      gnss_imu_c: "GNSS-IMU Sensor C",
      gnss_imu_d: "GNSS-IMU Sensor D",
      gnss_imu_e: "GNSS-IMU Sensor E",
      gnss_imu_f: "GNSS-IMU Sensor F",
      connect: "Connect",
      com_port: "COM port:",
      com2_port:"COM2 port:",
      com_baud_rate: "COM baud rate:",
      output_channel: "Output channel:",
      device_part: "Device",
      device_type:"Device type:",
      processing_part: "Processing",
      pitch_angle_offset: "Pitch angle offset:",
      yaw_rate: "Yaw rate offset:",
      pitch_offset: "Pitch offset:",
      roll_offset: "Roll offset:",
      novatel_imu_type:"Novatel IMU type:",
      time_type:"Time type:",
      heading_offset:"Heading Offset:",
      pos:"Pos(m):",
      connect_gps_comm:"Connect GPS Comm",
      send_command:"Send Command",
      connect_comm:"Connect command:"
  }