var cn = {
    add_signal: "添加信号触发式场景",
    enabled: "启用",
    not_config: "<未配置>",
    no_property: "无属性预设",
    trigger_condition: "触发条件:",
    end_condition: "结束条件:",
    cancel_condition: "取消条件:",
    begin_offset: "开始偏置[秒]:",
    end_offset: "结束偏置[秒]:",
    cancel_timeout: "超时取消[秒]:",
    edit_scene: "编辑场景ID",
    name: "名称:",
    signal_condition: "信号条件",
    signal: "信号:",
    error: "错误",
    the_repeat: "键不得重复",
    confim: "确定",
    key: "键",
    value: "值",
    config_property: "配置属性预设",
    Unknown: "未知场景",
    no_properzty:"无属性预设"
  },
  en = {
    key: "Key",
    value: "Value",
    confim: "Confim",
    the_repeat: "The Key should not be repeat.",
    error: "Error",
    add_signal: "Add signal triggered scene",
    enabled: "Enabled",
    no_property: "No property preset",
    not_config: "<Not Configured>",
    trigger_condition: "Trigger condition:",
    end_condition: "End condition:",
    cancel_condition: "Cancel condition:",
    begin_offset: "Begin offset [s]:",
    end_offset: "End offset [s]:",
    cancel_timeout: "Cancel timeout [s]:",
    edit_scene: "Edit Scene ID",
    name: "Name:",
    signal_condition: "Signal Condition",
    signal: "Signal:",
    config_property: "Config Property Preset",
    Unknown: "Unknown scene",
    no_properzty:"No Property Preset"
  };