var cn = {
  intrinsics: "内参设置",
  extrinsics: "外参设置",
  basic: "基础:",
  inversion: "倒置",
  vertical_flip: "镜像",
  undistort: "去畸变",
  reset: "重置",
  rectify: "对正:",
  roll: "横滚",
  pitch: "俯仰",
  yaw: "横摆",
  switch: "切换",
  channel: "视频通道:",
  input_mode: "输入模式:",
  recfps: "采集帧率:",
  aligned: "对齐帧率",
  generalsettings: "通用设定",
  size: "高清视频缓存大小[MB]:",
  thread: "最大处理线程数:",
  video_information: "检查视频设备插件",
  videodevices: "视频设备列表",
  channeloptions: "视频通道选项",
  fisheye_camera: "鱼眼摄像头参数设置",
  undefined: "不定义",
  any: "任意",
  front: "前向",
  origin: "原点[m]:",
  posture: "姿态[°]:",
  import_front: "导入",
  position: "摄像头位置:",
  left_side: "左侧盲区",
  right_side: "右侧盲区",
  import: "导入",
  p00_u: "P00-U坐标:",
  p04_u: "P04-U坐标:",
  p30_u: "P30-U坐标:",
  p34_u: "P34-U坐标:",
  p0h_ratio: "P0H比例:",
  ph0_ratio: "PH0比例:",
  p00_v: "P00-V坐标:",
  p04_v: "P04-V坐标:",
  p30_v: "P30-V坐标:",
  p34_v: "P34-V坐标:",
  p3h_ratio: "P3H比例:",
  ph4_ratio: "PH4比例:",
  zero_u: "原点U坐标:",
  zero_v: "原点V坐标:",
  meter_u: "单位U坐标:",
  meter_v: "单位V坐标:",
  fifty: "中点比例:",
  meter_scale: "缩放比例:",
  line_left: "左侧车道线",
  line_right: "右侧车道线",
  aspectratio: "像素纵横比[V/H]:",
  hfov_fisheye: "理想鱼眼横向视场角[deg]:",
  hfov: "横向视场角[deg]:",
  not_config: "无需配置",
  confirm: "确定",
  fisheye_intrinsics: "鱼眼模型内参",
  blind_spot_camera: "盲区摄像头参数设置",
  normal_camera_intrinsics: "针孔模型内参",
  normal_camera: "一般摄像头参数设置",
  intrinsics_import: "导入",
  intrinsics_export: "导出",
  switch_camera_type: "切换摄像头类型",
  lane_line_camera: "车道线摄像头参数设置",
  camera_type: "摄像头类型:",
  normal: "一般",
  lane_line: "车道线",
  blind_spot: "盲区",
  fisheye: "鱼眼",
  reset_param: "是否重置该视频通道参数？",
  error_file: '无效的标定参数文件',
  output_mode:"输出模式:"
},
  en = {
    intrinsics: "Intrinsics",
    extrinsics: "Extrinsics",
    basic: "Basic:",
    inversion: "Invert",
    vertical_flip: "V-flip",
    undistort: "Undistort",
    reset: "Reset",
    rectify: "Rectify:",
    roll: "Roll",
    pitch: "Pitch",
    yaw: "Yaw",
    switch: "Switch",
    channel: "Channel:",
    input_mode: "Input mode:",
    recfps: "Rec.FPS:",
    aligned: "Aligned FPS",
    generalsettings: "General settings",
    size: "Hi-res buffer size [MB]:",
    thread: "Max processing thread:",
    video_information: "Check video device plugins",
    videodevices: "Video devices",
    channeloptions: "Channel options",
    fisheye_camera: "Fisheye Camera",
    normal_camera: "Normal camera",
    normal_camera_intrinsics: "Pinhole intrinsics",
    undefined: "Undefined",
    any: "Any",
    front: "Front",
    origin: "Origin[m]:",
    posture: "Posture[°]:",
    import_front: "Import",
    position: "Position:",
    left_side: "Left side",
    right_side: "Right side",
    import: "Import",
    p00_u: "P00 -U:",
    p04_u: "P04-U:",
    p30_u: "P30-U:",
    p34_u: "P34-U:",
    p0h_ratio: "P0H-Ratio:",
    ph0_ratio: "PH0-Ratio:",
    p00_v: "P00-V:",
    p04_v: "P04-V:",
    p30_v: "P30-V:",
    p34_v: "P34-V:",
    p3h_ratio: "P3H-Ratio:",
    ph4_ratio: "PH4-Ratio:",
    zero_u: "Zero-U:",
    zero_v: "Zero-V:",
    meter_u: "One-U:",
    meter_v: "One-V:",
    fifty: "Ratio:",
    meter_scale: "Scale:",
    line_left: "Left side",
    line_right: "Right side",
    aspectratio: "Aspect ratio[V/H]:",
    hfov_fisheye: "Idel fisheyeHFOV[deg]:",
    hfov: "Horizontal FOV[deg]:",
    not_config: "Unnecessary to configure",
    confirm: "Confirm",
    fisheye_intrinsics: "Fisheye intrinsics",
    blind_spot_camera: "Blind spot camera",
    intrinsics_import: "Import",
    intrinsics_export: "Export",
    switch_camera_type: "Switch camera type",
    lane_line_camera: "Lane line camera",
    camera_type: "Camera type:",
    normal: "Normal",
    lane_line: "Lane line",
    blind_spot: "Blind spot",
    fisheye: "Fisheye",
    reset_param: "Are you sure to reset the parameters of the video channel?",
    error_file: 'Invalid calibration parameter file.',
    output_mode:"Output mode:"
  };