let cn = {
  rear: '背面',
  front: '正面',
  out_channel: '输出通道:',
  disabled: '(禁用)',
  object_sensor_a: '目标传感器A',
  object_sensor_b: '目标传感器B',
  object_sensor_c: '目标传感器C',
  object_sensor_d: '目标传感器D',
  object_sensor_e: '目标传感器E',
  object_sensor_f: '目标传感器F',
  object_sensor_g: '目标传感器G',
  object_sensor_h: '目标传感器H',
  object_sensor_i: '目标传感器I',
  object_sensor_j: '目标传感器J',
  object_sensor_k: '目标传感器K',
  object_sensor_l: '目标传感器L',
  object_sensor: '目标传感器 ',
  can_channel: 'CAN通道:',
  origin: '原点 [m]:',
  yaw_offset: 'yaw偏移[deg]:',
  post_process: '后处理',
  invert: '翻转'
},
  en = {
      rear: 'Rear',
      front: 'Front',
      out_channel: 'Output Channel:',
      disabled: '(Disabled)',
      object_sensor_a: 'Object sensor A',
      object_sensor_b: 'Object sensor B',
      object_sensor_c: 'Object sensor C',
      object_sensor_d: 'Object sensor D',
      object_sensor_e: 'Object sensor E',
      object_sensor_f: 'Object sensor F',
      object_sensor_g: 'Object sensor G',
      object_sensor_h: 'Object sensor H',
      object_sensor_i: 'Object sensor I',
      object_sensor_j: 'Object sensor J',
      object_sensor_k: 'Object sensor K',
      object_sensor_l: 'Object sensor L',
      can_channel: 'CAN Channel:',
      origin: 'Origin [m]:',
      yaw_offset: 'Yaw offset[deg]:',
      post_process: 'Post Process',
      invert: "Invert"
  };