var cn = {
  connect: "连接",
  ip: "IP:",
  port: "端口:",
  process: "处理",
  enabled: "启用",
  config_lane_line_bounds: "<配置车道线边界>",
  obj_out_channel: "目标物输出通道:",
  lane_out_channel: "车道线输出通道:",
  traffic_out_channel: "交通信息输出通道:",
  freespace_out_channel: "可行驶区域输出通道:",
  orign: "原点[m]:",
  horizion_camera: "QTest相机ID",
  rear_bound: "后端[m]",
  front_bound: "前端[m]",
  chan_a: "通道 A",
  chan_b: "通道 B",
  chan_c: "通道 C",
  chan_d: "通道 D",
  chan_e: "通道 E",
  chan_f: "通道 F",
  chan_g: "通道 G",
  chan_h: "通道 H",
  image_scaling: "图像缩放比例:",
  orign_size: "原点大小",
  size1: "1/2 大小",
  size2: "1/4 大小",
  disabled: "(禁用)",
  IsUseCalHeading: "是否计算朝向",
  arrive_time: "到达时间",
  local_time: "NTP当地时间",
  time_sync_mode: "SYNC时间模式:",
  Cam_object_output_channel:"相机目标物输出通道:",
  Front_Rdr_object_output_channel:"前雷达目标物输出通道:",
  Front_Vis_output_channel:"前Vis输出通道:",
  Vehicle_output_channel:"车辆输出通道:",
  Lane_output_channel:"车道线输出通道:",
  yaw_angle:"偏航",
  pitch:"倾斜度",
  roll:"旋转",
  pos_offset:"偏移位置[度]:"
},
  en = {
    disabled: "(Disabled)",
    image_scaling: "Image scaling ratio:",
    orign_size: "Origin size",
    size1: "1/2 size",
    size2: "1/4 size",
    chan_a: "Channel A",
    chan_b: "Channel B",
    chan_c: "Channel C",
    chan_d: "Channel D",
    chan_e: "Channel E",
    chan_f: "Channel F",
    chan_g: "Channel G",
    chan_h: "Channel H",
    connect: "Connection",
    ip: "IP:",
    port: "Port:",
    process: "Processing",
    enabled: "Enabled",
    config_lane_line_bounds: "<Configure lane line bounds>",
    obj_out_channel: "Object output channel:",
    lane_out_channel: "Lanes output channel:",
    traffic_out_channel: "Traffic output channel:",
    freespace_out_channel: "Freespace output channel:",
    orign: "Origin [m]:",
    horizion_camera: "QTest Camera ID",
    rear_bound: "Rear Bound [m]",
    front_bound: "Front Bound [m]",
    IsUseCalHeading: "IsUseCalHeading",
    arrive_time: "Arrival time",
    local_time: "NTP local time",
    time_sync_mode: "Time sync mode:",
    Cam_object_output_channel:"Cam object output channel:",
    Front_Rdr_object_output_channel:"Front Rdr object output channel:",
    Front_Vis_output_channel:"Front Vis output channel :",
    Vehicle_output_channel:"Vehicle output channel:",
    Lane_output_channel:"Lane output channel:",
    yaw_angle:"Yaw",
    pitch:"Pitch",
    roll:"Roll",
    pos_offset:"Pos offset[°]:"
  };