let cn = {
  out_channel: "输出通道:",
  can_channel: "CAN通道:",
  oringin: "原点 [m]:",
  yaw_offset: "Yaw偏移量 [deg]:",
  enabled: "启用",
  disabled: "(禁用)",
  obj_sen_a: "目标物传感器 A",
  obj_sen_b: "目标物传感器 B",
  obj_sen_c: "目标物传感器 C",
  obj_sen_d: "目标物传感器 D",
  obj_sen_e: "目标物传感器 E",
  obj_sen_f: "目标物传感器 F",
  obj_sen_g: "目标物传感器 G",
  obj_sen_h: "目标物传感器 H",
  obj_sen_i: "目标物传感器 I",
  obj_sen_j: "目标物传感器 J",
  obj_sen_k: "目标物传感器 K",
  obj_sen_l: "目标物传感器 L",
  value_x_scale: "X方向比例系数:",
  value_y_scale: "Y方向比例系数:",
  class_filter: "目标物类别过滤",
  select_in_signal: "选择输入信号:",
  signal_id_offset: "信号 ID 偏移量:",
  conf_filter: "置信度过滤",
},
en = {
  out_channel: "Output Channel:",
  can_channel: "CAN Channel:",
  origin: "Origin [m]:",
  yaw_offset: "Yaw offset [deg]:",
  enabled: "Enabled",
  disabled: "(Disabled)",
  obj_sen_a: "Object sensor A",
  obj_sen_b: "Object sensor B",
  obj_sen_c: "Object sensor C",
  obj_sen_d: "Object sensor D",
  obj_sen_e: "Object sensor E",
  obj_sen_f: "Object sensor F",
  obj_sen_g: "Object sensor G",
  obj_sen_h: "Object sensor H",
  obj_sen_i: "Object sensor I",
  obj_sen_j: "Object sensor J",
  obj_sen_k: "Object sensor K",
  obj_sen_l: "Object sensor L",
  value_x_scale: "ValueXScale:",
  value_y_scale: "ValueYScale:",
  class_filter: "ClassFilter",
  select_in_signal: "Select Input Signal:",
  signal_id_offset: "Signal ID Offset:",
  conf_filter: "ConfidenceFilter",
};