var cn = {
  enabled: "启动",
  channel: "通道:",
  frequency: "频率[Hz]:",
  trigger_value: "触发值[dB]:",
  send_signal: "Can总线发送报警信号",
  clear: "清空",
  IsNoiseReduce: "谱减法降噪",
  top: "(取前 ",
  SampleCount: "帧为噪声)",
  IsSampleReduce: "手动取样降噪",
  current: "(当前有 ",
  NoiseSamples: "个样本)",
  IsEnhance: "启用音频增强",
  EnhanceTimes: "增强倍率:",
  add: "添加",
  confirm: "确认",
  lower: "(下限)",
  upper: "(上限)",
  trigger: "触发值:",
  freq: "频率:",
  addFreq: "添加频率",
  clearSamples: "是否清空所有噪声样本?",
  Mode: "降噪模式:",
  none: "无",
  manual: "手动",
  auto: "自动",
  audio_analysis:"音频分析",
  noise_reduction:"降噪功能",
},
  en = {
    enabled: "Enabled",
    channel: "Channel:",
    frequency: "Frequency [Hz]:",
    trigger_value: "Trigger value [dB]:",
    send_signal: "Send signal by Can",
    clear: "Clear",
    IsNoiseReduce: "Spectral subtraction",
    top: "(Top ",
    SampleCount: "frames as sample)",
    IsSampleReduce: "Sampling method",
    current: "(Currently ",
    NoiseSamples: "Samples)",
    IsEnhance: "Audio enhance",
    EnhanceTimes: "Enhance times:",
    add: "Add",
    confirm: "Confirm",
    lower: "(Lower)",
    upper: "(Upper)",
    trigger: "Trigger value:",
    freq: "Frequency:",
    addFreq: "Add Frequency",
    clearSamples: "Are you sure to clear all noise samples?",
    Mode: "Noise reduction mode:",
    none: "None",
    manual: "Manual",
    auto: "Auto",
    audio_analysis:"Audio Analysis",
    noise_reduction:"Noise Reduction",
  };