let cn = {
    import: "导入",
    export: "导出",
    obj_sensor: "目标物传感器",
    enabled: "启用",
    out_channel: "输出通道:",
    object_a: "目标物传感器A",
    object_b: "目标物传感器B",
    object_c: "目标物传感器C",
    object_d: "目标物传感器D",
    object_e: "目标物传感器E",
    object_f: "目标物传感器F",
    object_g: "目标物传感器G",
    object_h: "目标物传感器H",
    object_i: "目标物传感器I",
    object_j: "目标物传感器J",
    object_k: "目标物传感器K",
    object_l: "目标物传感器L",
    sampling_msg: "帧尾报文:",
    not_config: "<未配置>",
    coordination: "坐标偏置",
    origin: "原点 [米]:",
    yam_offset: "横摆角偏置[deg]",
    fov_setting: "FOV设置",
    add_fov: "添加FOV",
    mode: "模式:",
    fix_class: "固定类别:",
    fix_class_2: "固定类别",
    by_class_signal: "类别信号",
    pedestrian: "行人:",
    car: "车辆:",
    truck: "卡车:",
    bike: "自行车:",
    car_1: "车辆",
    truck_1: "卡车",
    bike_1: "自行车",
    pedestrian_1: "行人",
    other_classes: "其他",
    position: "位置:",
    ClosestPoint: "最近点",
    BoxCenter: "框中心",
    d_value: "距离值:",
    dx_dy: "DX/DY",
    range_azimuth: "距离/方位",
    va_value: "速度/加速度值:",
    absolute: "绝对值",
    relative: "相对值",
    cipv: "关键目标(CIPV)",
    automatic: "自动",
    fixed_index: "固定序号",
    fixed_index_2: "固定序号:",
    by_index_signal: "序号信号",
    by_flag_signal: "标志位信号",
    index_signal: "序号信号",
    index_begin_from: "序号起始值:",
    left_side: "关键目标(左侧)",
    right_side: "关键目标(右侧)",
    object_signals: "目标物信号:",
    remove_all: "移除所有",
    duplicate: "复制",
    add: "添加",
    validation: "验证",
    valid_signal: "有效位信号:",
    valid_value: "有效值:",
    confidence: "置信度[%]:",
    flag_signal: "标志位信号:",
    flag_value: "标志位值:",
    properties: "属性",
    age: "年代:",
    object_box: "目标物框",
    width: "宽[米]:",
    length: "长[米]:",
    height: "高[米]:",
    object_classification: "目标物分类",
    fixed_class: "固定类别:",
    general_1: "一般",
    general: "一般:",
    class_signal: "类别信号:",
    general_category: "一般类别",
    general_small: "一般小目标:",
    general_big: "一般大目标:",
    barrier: "障碍物:",
    car_category: "车辆类别",
    van: "面包车:",
    minibus: "小巴:",
    bus: "大巴:",
    battery_cart: "四轮电瓶车:",
    pedestrian_category: "行人类别",
    adult: "成年人:",
    child: "小孩:",
    scooter: "平衡车:",
    truck_category: "卡车类别",
    minitruck: "小卡车:",
    container_truck: "货柜车:",
    bike_category: "自行车类别",
    motorbike: "摩托车:",
    bicycle: "自行车:",
    electric_bike: "电瓶车:",
    tricycle: "三轮车:",
    position_m: "位置[米]:",
    orientation: "朝向[°]",
    dist_range: "距离范围[m]:",
    source_object: "目标物来源:",
    message_id_offsets: "报文ID偏置值: #",
    cancel: "取消",
    validate: "验证",
    output_sample_version: "输出样本版本:",
    other_signals: "其他信号",
    object: "目标物 #",
    dx: "X轴位置[米]:",
    dy: "Y轴位置[米]:",
    orient: "朝向[°]:",
    angle_range: "角度范围[°]:",
    ok: "确定",
    fov_cfg: "FOV配置",
    confirm: "确定",
    yes: "是",
    no: "否",
    duplicate_object_settings: "复制目标物配置",
    message_id_offset: "报文ID偏置值",
    detail_obj: "目标物详情 #",
    final_msg: "帧尾报文:",
    obj_box: "目标物框",
    dz: "Z轴位置[米]:",
    vx: "X轴速度[KPH]:",
    vy: "Y轴速度[KPH]:",
    ax: "X轴加速度[m/s2]:",
    ay: "Y轴加速度[m/s2]:",
    heading: "朝向[deg]:",
    dx_sigma: "X轴位置sigma[米]:",
    dy_sigma: "Y轴位置sigma[米]:",
    dz_sigma: "Z轴位置sigma[米]:",
    tiny_car: "微型车:",
    wheel_chair: "轮椅:",
    cintainer_truck: "货柜车:",
    special_car: "特种汽车:",
    trailer: "拖车:",
    rail_car_category: "轨道车类别:",
    train: "火车:",
    tram: "有轨电车:",
    special_category: "特殊类别:",
    animal: "动物:",
    ball: "球:",
    litter: "垃圾:",
    on_road_static_category: "道路静态物类别",
    cone: "锥形警告路标:",
    manhole_cover: "井盖:",
    patch: "补丁:",
    gantry: "龙门架:",
    road_side_static_category: "路侧静态物类别",
    pole: "杆:",
    tree: "树:",
    vegetation: "植物:",
    building: "建筑:",
    edit: "修改",
    remove: "删除",
    replace_text: "被替换文本",
    id_offset: "ID偏置值",
    replace_with: "替换为",
    car_value: "汽车信号值:",
    ex_signals: "扩展信号",
    rcs:"RCS [dB]:"
  },
  en = {
    ex_signals: "Extension signals",
    car_value: "Car value:",
    id_offset: "ID offset",
    replace_with: "Replace with",
    replace_text: "Replaced text:",
    edit: "Edit",
    remove: "Remove",
    pole: "Pole:",
    tree: "Tree:",
    vegetation: "Vegetation:",
    building: "Building:",
    vx: "VX[KPH]:",
    vy: "VY[KPH]:",
    ax: "AX[m/s2]:",
    ay: "AY[m/s2]:",
    heading: "Heading [deg]:",
    height: "Height[m]:",
    length: "Length [m]:",
    width: "Width [m]:",
    obj_box: "Object box",
    detail_obj: "Details of object #",
    yes: "Yes",
    no: "No",
    confirm: "Confirm",
    fov_cfg: "FOV Configuration",
    ok: "OK",
    angle_range: "Angle range [°]:",
    orient: "Orientation [°]:",
    position_m: "Position [m]:",
    dx: "DX [m]:",
    dy: "DY [m]:",
    object: "Object #",
    other_signals: "Other signals",
    output_sample_version: "Output sample version:",
    import: "Import",
    export: "Export",
    obj_sensor: "Object Sensor",
    enabled: "Enabled",
    out_channel: "Output Channel:",
    object_a: "Object Sensor A",
    object_b: "Object Sensor B",
    object_c: "Object Sensor C",
    object_d: "Object Sensor D",
    object_e: "Object Sensor E",
    object_f: "Object Sensor F",
    object_g: "Object Sensor G",
    object_h: "Object Sensor H",
    object_i: "Object Sensor I",
    object_j: "Object Sensor J",
    object_k: "Object Sensor K",
    object_l: "Object Sensor L",
    sampling_msg: "Final msg:",
    not_config: "<Not Configured>",
    coordination: "Coordination offset",
    origin: "Origin [m]:",
    yam_offset: "Yaw offset [deg]:",
    fov_setting: "FOV settings",
    add_fov: "Add FOV",
    mode: "Mode:",
    fix_class: "Fixed class:",
    fix_class_2: "Fixed class",
    by_class_signal: "By class signal",
    other_classes: "Values of other classes",
    position: "Position:",
    ClosestPoint: "Closest point",
    BoxCenter: "Box center",
    d_value: "D value:",
    dx_dy: "DX/DY",
    range_azimuth: "Range/Azimuth",
    va_value: "V/A value:",
    absolute: "Absolute",
    relative: "Relative",
    cipv: "Key object(CIPV)",
    automatic: "Automatic",
    fixed_index: "Fixed index",
    fixed_index_2: "Fixed index:",
    by_index_signal: "By index signal",
    by_flag_signal: "By flag signal",
    index_signal: "Index signal:",
    index_begin_from: "Index begins from:",
    left_side: "Key object(Left-side)",
    right_side: "Key object(Right-side)",
    object_signals: "Object signals:",
    remove_all: "Remove all",
    duplicate: "Duplicate",
    add: "Add",
    validation: "Validation",
    valid_value: "Valid value:",
    flag_signal: "Flag signal:",
    flag_value: "Flag value:",
    properties: "Properties",
    age: "Age:",
    dz: "DZ[m]:",
    dx_sigma: "DX-sigma [m]:",
    dy_sigma: "DY-sigma [m]:",
    dz_sigma: "DZ-sigma [m]:",
    object_box: "Object box",
    object_classification: "Object classification",
    fixed_class: "Fixed class:",
    general_1: "General",
    car_1: "Car",
    pedestrian_1: "Pedestrian",
    truck_1: "Truck",
    bike_1: "Bike",
    general: "General:",
    car: "Car:",
    pedestrian: "Pedestrian:",
    truck: "Truck:",
    bike: "Bike:",
    class_signal: "Class signal:",
    general_category: "General category",
    general_small: "General small:",
    general_big: "General big:",
    barrier: "Barrier:",
    car_category: "Car category",
    van: "Van:",
    minibus: "Minibus:",
    bus: "Bus:",
    battery_cart: "Battery cart:",
    pedestrian_category: "Pedestrian category",
    adult: "Adult:",
    child: "Child:",
    scooter: "Scooter:",
    truck_category: "Truck category",
    minitruck: "Minitruck:",
    container_truck: "Container truck:",
    bike_category: "Bike category",
    motorbike: "Motorbike:",
    bicycle: "Bicycle:",
    electric_bike: "Electric bike:",
    tricycle: "Tricycle:",
    orientation: "orientation [°]",
    dist_range: "Dist range [m]:",
    message_id_offsets: "Message ID offsets: #",
    cancel: "Cancel",
    validate: "Validate",
    tiny_car: "Tiny car:",
    wheel_chair: "Wheel chair:",
    cintainer_truck: "Container truck:",
    special_car: "Special car:",
    trailer: "Trailer:",
    rail_car_category: "Rail car category:",
    train: "Train:",
    tram: "Tram:",
    special_category: "Special category:",
    animal: "Animal:",
    ball: "Ball:",
    litter: "Litter:",
    on_road_static_category: "On-road static category",
    cone: "Cone:",
    manhole_cover: "Manhole cover:",
    patch: "Patch:",
    gantry: "Gantry:",
    road_side_static_category: "Road-side static category",
    duplicate_object_settings: "Duplicate object settings",
    source_object: "Source object",
    message_id_offset: "Message ID offsets:",
    final_msg: "Final msg:",
    valid_signal: "Valid signal:",
    confidence: "Confidence [%]:",
    rcs:"RCS [dB]:"
  }