var cn = {
  enable: "启动",
  select_scene: "选择场景",
  cut_in: "切入",
  overtake: "超车",
  cut_out: "切出",
  car_following: "跟车",
  lane_change: "变道",
  lane_keep: "车道保持",
  u_turn: "掉头",
  lane_source: "车道线通道:",
  object_source: "目标物通道:",
  com_par: "通用参数和通道",
  tube_width: "Tube宽度 [m]:",
  max_curv: "最大曲率 [1/m]:",
  rang_dis: "距离范围 [m]:",
  car_foll_par: "跟车参数",
  en_thw: "进入跟车THW[s]: <",
  en_vx_rel: "进入跟车相对速度[km/h]: <",
  le_thw: "结束跟车THW[s]: >",
  le_vx_rel: "结束跟车相对速度[km/h]: >",
  cut_in_out: "切入/切出 参数",
  cut_in_over: "切入重叠率[%]: >",
  cut_out_over: "切出重叠率[%]: <",
  disabled: "禁用",
  sen_a: "传感器 A",
  sen_b: "传感器 B",
  sen_c: "传感器 C",
  sen_d: "传感器 D",
  sen_e: "传感器 E",
  sen_f: "传感器 F",
  sen_g: "传感器 G",
  sen_h: "传感器 H",
  sen_i: "传感器 I",
  sen_j: "传感器 J",
  sen_k: "传感器 K",
  sen_l: "传感器 L",
  turn_left_enable:"左转",
  turn_right_enable:"右转",
  gnssimu_source:"组合惯导来源:",
  turn_left:"左/右转"
},
en = {
  disabled: "Disabled",
  sen_a: "Sensor A",
  sen_b: "Sensor B",
  sen_c: "Sensor C",
  sen_d: "Sensor D",
  sen_e: "Sensor E",
  sen_f: "Sensor F",
  sen_g: "Sensor G",
  sen_h: "Sensor H",
  sen_i: "Sensor I",
  sen_j: "Sensor J",
  sen_k: "Sensor K",
  sen_l: "Sensor L",
  enable: "Enable",
  select_scene: "Select Scene",
  cut_in: "Cut-in",
  overtake: "Overtake",
  cut_out: "Cut-out",
  car_following: "Car-following",
  lane_change: "Lane-change",
  lane_keep: "Lane-keep",
  u_turn: "U-turn",
  lane_source: "Lane Source:",
  object_source: "Object Source:",
  com_par: "Common Parameter And Channel",
  tube_width: "Tube Width [m]:",
  max_curv: "Max Curvature [1/m]:",
  rang_dis: "Range Distance [m]:",
  car_foll_par: "Car-follwing Parameter",
  en_thw: "Enter THW [s]: <",
  en_vx_rel: "Enter Vx Relative [km/h]: <",
  le_thw: "Leave THW [s]: >",
  le_vx_rel: "Leave Vx Relative [km/h]: >",
  cut_in_out: "Cut-in/out Parameter",
  cut_in_over: "Cut-in Overlap [%]: >",
  cut_out_over: "Cut-out Overlap [%]: <",
  turn_left_enable:"Turn Left",
  turn_right_enable:"Turn right",
  gnssimu_source:"GNSS-IMU Source:",
  turn_left:"Turn Left/Right"
}
